"""
MermaidDiagramGenerator -- generates Mermaid diagrams from static analysis data.

Parses .arch.md files to extract structured data (repo name, primary language,
LOC, tech stack, language breakdown, module structure, APIs, events, databases,
service dependencies, infrastructure resources, authentication) and produces
rich diagram types including architecture overviews, infrastructure layouts,
and sequence diagrams as a combined markdown document.

No AI required -- purely programmatic graph/chart construction.
"""

import re
from collections import defaultdict
from datetime import datetime

# Mapping from resource category to AWS service node for overview diagram
_SERVICE_MAP = {
    "Networking": {"id": "svc_VPC", "display": "AWS VPC\nVirtual Private Cloud", "category": "security"},
    "Compute/EMR": {"id": "svc_EMR", "display": "AWS EMR\nElastic MapReduce", "category": "compute"},
    "Compute/EC2": {"id": "svc_EC2", "display": "AWS EC2\nInstances", "category": "compute"},
    "Compute/Lambda": {"id": "svc_Lambda", "display": "AWS Lambda", "category": "compute"},
    "Compute/ECS": {"id": "svc_ECS", "display": "AWS ECS", "category": "compute"},
    "IAM": {"id": "svc_IAM", "display": "AWS IAM\nIdentity & Access", "category": "security"},
    "Security": {"id": "svc_SG", "display": "Security Groups", "category": "security"},
    "Load Balancing": {"id": "svc_ELB", "display": "AWS ELB\nLoad Balancer", "category": "service"},
    "Storage/S3": {"id": "svc_S3", "display": "S3\nData Storage", "category": "storage"},
    "Storage/EBS": {"id": "svc_EBS", "display": "AWS EBS", "category": "storage"},
    "Database/RDS": {"id": "svc_RDS", "display": "Amazon RDS", "category": "storage"},
    "Database/DynamoDB": {"id": "svc_DynamoDB", "display": "DynamoDB", "category": "storage"},
    "Monitoring": {"id": "svc_CW", "display": "CloudWatch", "category": "service"},
}

# VPC endpoint names that imply additional AWS service nodes
_VPC_ENDPOINT_SERVICE_MAP = {
    "s3": {"id": "svc_S3", "display": "S3\nData Storage", "category": "storage"},
    "dynamodb": {"id": "svc_DynamoDB", "display": "DynamoDB", "category": "storage"},
    "kinesis_streams": {"id": "svc_Kinesis", "display": "Kinesis\nStreams", "category": "service"},
    "kinesis": {"id": "svc_Kinesis", "display": "Kinesis\nStreams", "category": "service"},
}

# Service-to-service structural edges (added when both nodes exist)
_SERVICE_EDGES = [
    ("svc_EMR", "svc_VPC", "runs within"),
    ("svc_EMR", "svc_S3", "reads/writes"),
    ("svc_EMR", "svc_IAM", "uses roles"),
    ("svc_EC2", "svc_VPC", "runs within"),
    ("svc_EC2", "svc_IAM", "uses roles"),
    ("svc_VPC", "svc_SG", "protected by"),
    ("svc_Lambda", "svc_IAM", "uses roles"),
    ("svc_ECS", "svc_VPC", "runs within"),
]

# Mapping from resource category keywords to architectural layer
_LAYER_MAP = {
    "Networking": "network",
    "Security": "security",
    "IAM": "security",
    "Compute/EC2": "compute",
    "Compute/EMR": "compute",
    "Compute/Lambda": "compute",
    "Compute/ECS": "compute",
    "Compute/EKS": "compute",
    "Load Balancing": "loadbalancing",
    "Storage/S3": "storage",
    "Storage/EBS": "storage",
    "Database/RDS": "storage",
    "Database/DynamoDB": "storage",
    "Monitoring": "monitoring",
}


class MermaidDiagramGenerator:
    """Generates Mermaid diagrams from static analysis .arch.md content."""

    def __init__(self, repo_contents: dict[str, str]):
        """
        Args:
            repo_contents: dict mapping repo_name -> arch.md content string
        """
        self.repo_contents = repo_contents
        self._parsed_repos: list[dict] = []

        for repo_name, content in repo_contents.items():
            parsed = self._parse_repo_data(repo_name, content)
            if parsed:
                self._parsed_repos.append(parsed)

    def generate_all(self, generated_date: str | None = None) -> str:
        """Generate all diagrams, return as combined markdown document.

        Args:
            generated_date: Optional date string for the header. If None, uses today.
        """
        if not self._parsed_repos:
            return self._empty_document(generated_date)

        date_str = generated_date or datetime.now().strftime("%Y-%m-%d")

        sections = [
            "# Cross-Repository Architecture Overview",
            "",
            "This document was automatically generated by RepoSwarm's static analysis.",
            f"Generated on: {date_str}",
            "",
            "---",
            "",
        ]

        # Diagram 0: Cross-Repo Lifecycle (overarching view of all repos)
        lifecycle = self._generate_cross_repo_lifecycle_diagram()
        if lifecycle:
            sections.append("## Cross-Repository Lifecycle")
            sections.append("")
            sections.append(lifecycle)
            sections.append("")

        # Diagram 1: Repository Overview (enriched with connections)
        overview = self._generate_overview_diagram()
        if overview:
            sections.append("## Network/Architecture Diagram")
            sections.append("")
            sections.append(overview)
            sections.append("")

        # Key Connections narrative (after overview)
        key_connections = self._generate_key_connections_narrative()
        if key_connections:
            sections.append(key_connections)
            sections.append("")

        # Diagram 2: Technology Stack
        tech_stack = self._generate_tech_stack_diagram()
        if tech_stack:
            sections.append("## Technology Stack")
            sections.append("")
            sections.append(tech_stack)
            sections.append("")

        # Diagram 3: Infrastructure Architecture
        infra = self._generate_infrastructure_diagram()
        if infra:
            sections.append("## Infrastructure Architecture")
            sections.append("")
            sections.append(infra)
            sections.append("")

        # Diagram 4: Data Flow
        data_flow = self._generate_data_flow_diagram()
        if data_flow:
            sections.append("## Data Flow")
            sections.append("")
            sections.append(data_flow)
            sections.append("")

            # Data Flow Summary (after data flow diagram)
            summary = self._generate_data_flow_summary()
            if summary:
                sections.append(summary)
                sections.append("")

            # Data Governance Concerns
            governance = self._generate_governance_concerns()
            if governance:
                sections.append(governance)
                sections.append("")

        # Diagram 5: Module Structure (per-repo)
        module_diagrams = self._generate_module_diagrams()
        if module_diagrams:
            sections.append("## Module Structure")
            sections.append("")
            sections.append(module_diagrams)
            sections.append("")

        # Diagram 6: Language Distribution
        pie_chart = self._generate_language_pie_chart()
        if pie_chart:
            sections.append("## Language Distribution")
            sections.append("")
            sections.append(pie_chart)
            sections.append("")

        # Diagram 7+: Sequence Diagrams (enriched)
        sequence = self._generate_sequence_diagrams()
        if sequence:
            sections.append("## Service Interaction Sequences")
            sections.append("")
            sections.append(sequence)
            sections.append("")

        sections.append("---")
        sections.append("*Generated by static analysis (ENABLE_AI=false)*")

        return "\n".join(sections)

    # ------------------------------------------------------------------
    # Parsing
    # ------------------------------------------------------------------

    def _parse_repo_data(self, repo_name: str, content: str) -> dict | None:
        """Extract structured data from an .arch.md file."""
        if not content or not content.strip():
            return None

        data = {
            "repo_name": repo_name,
            "display_name": repo_name,
            "primary_language": "Unknown",
            "total_loc": 0,
            "total_files": 0,
            "tech_stack": [],
            "languages": {},  # {lang: loc}
            "modules": [],    # [{name, files, subdirs}]
            "api_endpoints": [],  # [{method, path, detail}]
            "event_brokers": [],  # ["Kafka", "RabbitMQ", ...]
            "event_topics": [],   # [{name, type}]
            "databases": [],      # ["PostgreSQL", "DynamoDB", ...]
            "module_chain": [],   # [{name, source}]
            "outputs": [],        # [{name, file}]
            "terraform_resources": [],  # [{type, name, category, file}]
            "resource_categories": {},  # {category: count}
            "iam_resources": [],        # [{type, name, file}]
            "security_resources": [],   # [{type, name, category, file}]
            "resource_groups": [],      # [{group, resources, files}]
            "providers": [],            # ["aws", "google", ...]
        }

        # Extract repo name from content (may differ from filename key)
        name_match = re.search(
            r'\*\*Repository Name:\*\*\s*(.+)', content
        )
        if name_match:
            data["display_name"] = name_match.group(1).strip()

        # Primary language
        lang_match = re.search(
            r'\*\*Primary Language:\*\*\s*(.+)', content
        )
        if lang_match:
            data["primary_language"] = lang_match.group(1).strip()

        # Total LOC
        loc_match = re.search(
            r'\*\*Total Lines of Code:\*\*\s*([\d,]+)', content
        )
        if loc_match:
            data["total_loc"] = int(loc_match.group(1).replace(",", ""))

        # Total files
        files_match = re.search(
            r'\*\*Total Files:\*\*\s*([\d,]+)', content
        )
        if files_match:
            data["total_files"] = int(files_match.group(1).replace(",", ""))

        # Tech stack (lines starting with "- " after **Technology Stack:**)
        tech_match = re.search(
            r'\*\*Technology Stack:\*\*\s*\n((?:\s*-\s*.+\n?)+)', content
        )
        if tech_match:
            tech_block = tech_match.group(1)
            data["tech_stack"] = [
                line.strip().lstrip("- ").strip()
                for line in tech_block.strip().split("\n")
                if line.strip().startswith("-")
            ]

        # Language breakdown table
        # | Language | Files | Lines of Code | Blank | Comment |
        lang_table_match = re.search(
            r'\*\*Language Breakdown:\*\*\s*\n'
            r'\s*\|[^\n]*Language[^\n]*\|\s*\n'  # header
            r'\s*\|[-| :]+\|\s*\n'                # separator
            r'((?:\s*\|[^\n]+\|\s*\n?)+)',          # rows
            content,
        )
        if lang_table_match:
            rows_text = lang_table_match.group(1)
            for row in rows_text.strip().split("\n"):
                cells = [c.strip() for c in row.strip().strip("|").split("|")]
                if len(cells) >= 3:
                    lang = cells[0].strip()
                    try:
                        loc = int(cells[2].strip().replace(",", ""))
                        if lang and loc >= 0:
                            data["languages"][lang] = loc
                    except (ValueError, IndexError):
                        pass

        # Module/directory breakdown table
        # | Module | Files | Subdirectories |
        module_match = re.search(
            r'\*\*Module/Directory Breakdown:\*\*\s*\n'
            r'\s*\|[^\n]*Module[^\n]*\|\s*\n'     # header
            r'\s*\|[-| :]+\|\s*\n'                  # separator
            r'((?:\s*\|[^\n]+\|\s*\n?)+)',            # rows
            content,
        )
        if module_match:
            rows_text = module_match.group(1)
            for row in rows_text.strip().split("\n"):
                cells = [c.strip() for c in row.strip().strip("|").split("|")]
                if len(cells) >= 2:
                    mod_name = cells[0].strip().strip("`").rstrip("/")
                    try:
                        files_count = int(cells[1].strip())
                    except (ValueError, IndexError):
                        files_count = 0
                    try:
                        subdirs = int(cells[2].strip()) if len(cells) >= 3 else 0
                    except (ValueError, IndexError):
                        subdirs = 0
                    if mod_name:
                        data["modules"].append({
                            "name": mod_name,
                            "files": files_count,
                            "subdirs": subdirs,
                        })

        # --- Parse APIs section ---
        apis_section = self._extract_section(content, "APIs")
        if apis_section and "*No " not in apis_section[:20]:
            # Match: | METHOD | `path` | detail |
            api_re = re.compile(
                r'\|\s*(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS|ANY)\s*\|'
                r'\s*`?([^|`]+)`?\s*\|'
                r'\s*([^|]*)\|',
                re.IGNORECASE,
            )
            for m in api_re.finditer(apis_section):
                data["api_endpoints"].append({
                    "method": m.group(1).upper().strip(),
                    "path": m.group(2).strip(),
                    "detail": m.group(3).strip(),
                })

        # --- Parse events section ---
        events_section = self._extract_section(content, "events")
        if events_section and "*No " not in events_section[:20]:
            # Broker names from bullet list: - **Kafka**
            broker_re = re.compile(r'^\s*-\s*\*\*([^*]+)\*\*', re.MULTILINE)
            for m in broker_re.finditer(events_section):
                broker = m.group(1).strip()
                if broker not in data["event_brokers"]:
                    data["event_brokers"].append(broker)

            # Topics from table: | `topic.name` | type | file |
            # Only parse after **Topics/Queues:** header
            topics_block = ""
            topics_header = re.search(r'\*\*Topics/Queues:\*\*', events_section)
            if topics_header:
                topics_block = events_section[topics_header.end():]
                # Stop at next header
                next_header = re.search(r'\n\*\*[A-Z]', topics_block)
                if next_header:
                    topics_block = topics_block[:next_header.start()]

            if topics_block:
                topic_re = re.compile(r'\|\s*`([^`]+)`\s*\|\s*([^|]+)\|')
                for m in topic_re.finditer(topics_block):
                    data["event_topics"].append({
                        "name": m.group(1).strip(),
                        "type": m.group(2).strip(),
                    })

        # --- Parse DBs section ---
        dbs_section = self._extract_section(content, "DBs")
        if dbs_section and "*No " not in dbs_section[:20]:
            db_types = set()
            db_row_re = re.compile(
                r'^\s*\|\s*`?([A-Z][\w\s/]+[\w])`?\s*\|',
                re.MULTILINE,
            )
            for m in db_row_re.finditer(dbs_section):
                db_type = m.group(1).strip().strip("`")
                if db_type.lower() not in ("type", "name", "database", "database type",
                                           "resource type", "schema type"):
                    db_types.add(db_type)

            data["databases"] = sorted(db_types)

        # --- Parse service_dependencies section ---
        svc_section = self._extract_section(content, "service_dependencies")
        if svc_section and "*No " not in svc_section[:20]:
            # Module chain: root -> module_name (source: ./path)
            chain_re = re.compile(r'root\s*->\s*(\S+)\s*\(source:\s*([^)]+)\)')
            for m in chain_re.finditer(svc_section):
                data["module_chain"].append({
                    "name": m.group(1).strip(),
                    "source": m.group(2).strip(),
                })

            # Outputs: - `name` (file)
            output_re = re.compile(r'-\s*`([^`]+)`\s*\(([^)]+)\)')
            outputs_header = re.search(r'\*\*Outputs Exposed:\*\*', svc_section)
            if outputs_header:
                outputs_block = svc_section[outputs_header.end():]
                for m in output_re.finditer(outputs_block):
                    data["outputs"].append({
                        "name": m.group(1).strip(),
                        "file": m.group(2).strip(),
                    })

            # Providers: | `aws` | main.tf |
            provider_re = re.compile(r'\|\s*`([^`]+)`\s*\|', re.MULTILINE)
            providers_header = re.search(r'\*\*Providers:\*\*', svc_section)
            if providers_header:
                providers_block = svc_section[providers_header.end():]
                next_header = re.search(r'\n\*\*[A-Z]', providers_block)
                if next_header:
                    providers_block = providers_block[:next_header.start()]
                for m in provider_re.finditer(providers_block):
                    prov = m.group(1).strip()
                    if prov.lower() not in ("provider", "module", "source"):
                        data["providers"].append(prov)

        # --- Parse resources section ---
        self._parse_resources_section(content, data)

        # --- Parse authentication section ---
        self._parse_authentication_section(content, data)

        # --- Parse authorization section ---
        self._parse_authorization_section(content, data)

        # --- Parse core_entities section ---
        self._parse_core_entities_section(content, data)

        return data

    def _parse_resources_section(self, content: str, data: dict) -> None:
        """Parse the # resources section for Terraform infrastructure resources."""
        resources_section = self._extract_section(content, "resources")
        if not resources_section or "*No " in resources_section[:20]:
            return

        # Individual resources: | `aws_vpc` | main | Networking | main.tf |
        res_re = re.compile(
            r'\|\s*`([^`]+)`\s*\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|'
        )
        for m in res_re.finditer(resources_section):
            res_type = m.group(1).strip()
            res_name = m.group(2).strip()
            category = m.group(3).strip()
            file_path = m.group(4).strip()
            # Skip header rows
            if res_type.lower() in ("resource type",):
                continue
            data["terraform_resources"].append({
                "type": res_type,
                "name": res_name,
                "category": category,
                "file": file_path,
            })

        # Category summary: | Networking | 18 |
        cat_header = re.search(r'\*\*Resources by Category:\*\*', resources_section)
        if cat_header:
            cat_block = resources_section[cat_header.end():]
            next_header = re.search(r'\n\*\*[A-Z]', cat_block)
            if next_header:
                cat_block = cat_block[:next_header.start()]
            cat_re = re.compile(r'\|\s*([A-Za-z][^|]+?)\s*\|\s*(\d+)\s*\|')
            for m in cat_re.finditer(cat_block):
                cat_name = m.group(1).strip()
                if cat_name.lower() not in ("category", "count"):
                    try:
                        data["resource_categories"][cat_name] = int(m.group(2))
                    except ValueError:
                        pass

    def _parse_authentication_section(self, content: str, data: dict) -> None:
        """Parse the # authentication section for IAM resources."""
        auth_section = self._extract_section(content, "authentication")
        if not auth_section or "*No " in auth_section[:20]:
            return

        # | `aws_iam_role` | emr_iam_role | emr/emr.tf |
        iam_re = re.compile(
            r'\|\s*`([^`]+)`\s*\|\s*([^|]+)\|\s*([^|]+)\|'
        )
        for m in iam_re.finditer(auth_section):
            res_type = m.group(1).strip()
            res_name = m.group(2).strip()
            file_path = m.group(3).strip()
            if res_type.lower() in ("resource type",):
                continue
            data["iam_resources"].append({
                "type": res_type,
                "name": res_name,
                "file": file_path,
            })

    def _parse_authorization_section(self, content: str, data: dict) -> None:
        """Parse the # authorization section for security resources."""
        authz_section = self._extract_section(content, "authorization")
        if not authz_section or "*No " in authz_section[:20]:
            return

        # | `aws_security_group` | sg_1 | Security | vpc/vpc.tf |
        sec_re = re.compile(
            r'\|\s*`([^`]+)`\s*\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|'
        )
        for m in sec_re.finditer(authz_section):
            res_type = m.group(1).strip()
            res_name = m.group(2).strip()
            category = m.group(3).strip()
            file_path = m.group(4).strip()
            if res_type.lower() in ("resource type",):
                continue
            data["security_resources"].append({
                "type": res_type,
                "name": res_name,
                "category": category,
                "file": file_path,
            })

    def _parse_core_entities_section(self, content: str, data: dict) -> None:
        """Parse the # core_entities section for Terraform resource groups."""
        entities_section = self._extract_section(content, "core_entities")
        if not entities_section or "*No " in entities_section[:20]:
            return

        # | Vpc | 7 | vpc/vpc.tf, bastion/bastion.tf |
        group_re = re.compile(
            r'\|\s*([A-Z][a-zA-Z_]+)\s*\|\s*(\d+)\s*\|\s*([^|]+)\|'
        )
        for m in group_re.finditer(entities_section):
            group_name = m.group(1).strip()
            if group_name.lower() in ("group", "resources"):
                continue
            try:
                count = int(m.group(2))
            except ValueError:
                count = 0
            data["resource_groups"].append({
                "group": group_name,
                "resources": count,
                "files": m.group(3).strip(),
            })

    # ------------------------------------------------------------------
    # Styling Helpers
    # ------------------------------------------------------------------

    def _get_style_definitions(self) -> list[str]:
        """Return classDef lines for diagram styling."""
        return [
            "classDef iacNode fill:#e6ccff,stroke:#6600cc,stroke-width:2px",
            "classDef serviceNode fill:#ccffcc,stroke:#006600,stroke-width:2px",
            "classDef dataNode fill:#cce5ff,stroke:#0066cc,stroke-width:2px",
            "classDef securityNode fill:#ffffcc,stroke:#cccc00,stroke-width:2px",
            "classDef computeNode fill:#ffe6cc,stroke:#cc6600,stroke-width:2px",
            "classDef networkNode fill:#e6f3ff,stroke:#3399cc,stroke-width:2px",
        ]

    def _classify_repo(self, repo_data: dict) -> str:
        """Classify a repo by its primary role."""
        lang = repo_data["primary_language"].lower()
        if lang in ("terraform", "cloudformation", "pulumi") or repo_data["module_chain"]:
            return "iac"
        if repo_data["api_endpoints"]:
            return "service"
        if repo_data["event_brokers"] or repo_data["event_topics"]:
            return "event_processor"
        if repo_data["databases"]:
            return "data"
        return "library"

    def _node_shape(self, node_id: str, label: str, category: str) -> str:
        """Return Mermaid node with appropriate shape for the category."""
        if category == "storage":
            return f'{node_id}[("{label}")]'
        if category == "compute":
            return f'{node_id}{{{{"{label}"}}}}'
        if category == "service":
            return f'{node_id}("{label}")'
        if category == "security":
            return f'{node_id}{{{{"{label}"}}}}'
        if category == "broker":
            return f'{node_id}(["{label}"])'
        if category == "user":
            return f'{node_id}(("{label}"))'
        return f'{node_id}["{label}"]'

    def _infer_repo_connections(self) -> list[tuple]:
        """Infer cross-repo connections from shared data.

        Returns list of (from_idx, to_idx, label, style) where style is
        "solid" or "dotted".
        """
        connections = []
        seen = set()  # (from_idx, to_idx, connection_type) to allow multiple edge types

        # Shared module sources (e.g. both repos use ./vpc module)
        source_to_repos: dict[str, list[int]] = defaultdict(list)
        for i, repo in enumerate(self._parsed_repos):
            for mod in repo["module_chain"]:
                source_to_repos[mod["source"]].append(i)
        for source, indices in source_to_repos.items():
            if len(indices) > 1:
                mod_name = source.lstrip("./")
                for j in range(1, len(indices)):
                    key = (indices[0], indices[j], "module")
                    if key not in seen:
                        seen.add(key)
                        connections.append(
                            (indices[0], indices[j], f"shared {mod_name} module", "dotted")
                        )

        # Shared resource categories
        cat_to_repos: dict[str, list[int]] = defaultdict(list)
        for i, repo in enumerate(self._parsed_repos):
            for cat in repo["resource_categories"]:
                cat_to_repos[cat].append(i)
        for cat, indices in cat_to_repos.items():
            if len(indices) > 1:
                for j in range(1, len(indices)):
                    key = (indices[0], indices[j], "resource")
                    if key not in seen:
                        seen.add(key)
                        connections.append(
                            (indices[0], indices[j], f"shared {cat} resources", "dotted")
                        )

        # Shared event topics (cross-repo pub/sub)
        topic_to_repos: dict[str, list[int]] = defaultdict(list)
        for i, repo in enumerate(self._parsed_repos):
            for topic in repo["event_topics"]:
                topic_to_repos[topic["name"]].append(i)
        for topic, indices in topic_to_repos.items():
            if len(indices) > 1:
                key = (indices[0], indices[1], "event")
                if key not in seen:
                    seen.add(key)
                    connections.append(
                        (indices[0], indices[1], f"event: {topic}", "solid")
                    )

        # Shared database types
        db_to_repos: dict[str, list[int]] = defaultdict(list)
        for i, repo in enumerate(self._parsed_repos):
            for db in repo["databases"]:
                db_to_repos[db].append(i)
        for db, indices in db_to_repos.items():
            if len(indices) > 1:
                key = (indices[0], indices[1], "db")
                if key not in seen:
                    seen.add(key)
                    connections.append(
                        (indices[0], indices[1], f"shared {db}", "dotted")
                    )

        return connections

    # ------------------------------------------------------------------
    # Diagram Generators
    # ------------------------------------------------------------------

    def _generate_cross_repo_lifecycle_diagram(self) -> str:
        """Diagram 0: Overarching view showing how all repos work together in the lifecycle."""
        if len(self._parsed_repos) < 2:
            return ""

        # Classify repos and determine their roles
        repo_roles = []
        for i, repo in enumerate(self._parsed_repos):
            role = {
                "idx": i,
                "name": repo["display_name"],
                "node_id": self._safe_id(repo["display_name"], i),
                "has_vpc": "Networking" in repo["resource_categories"],
                "has_emr": "Compute/EMR" in repo["resource_categories"],
                "has_cf": any("cloudformation" in r["type"] for r in repo["terraform_resources"]),
                "has_ec2": "Compute/EC2" in repo["resource_categories"],
                "has_iam": "IAM" in repo["resource_categories"],
                "modules": [m["name"] for m in repo["module_chain"]],
                "primary_lang": repo["primary_language"],
                "loc": repo["total_loc"],
            }
            repo_roles.append(role)

        lines = [
            "```mermaid",
            "---",
            "title: Cross-Repository Lifecycle — How All Repos Work Together",
            "---",
            "graph LR",
        ]

        # Create repo nodes with descriptive labels
        for role in repo_roles:
            desc_parts = []
            if role["has_vpc"]:
                desc_parts.append("VPC")
            if role["has_emr"]:
                desc_parts.append("EMR")
            if role["has_cf"]:
                desc_parts.append("CloudFormation")
            if role["has_ec2"]:
                desc_parts.append("EC2")
            if role["has_iam"]:
                desc_parts.append("IAM")

            resource_summary = ", ".join(desc_parts) if desc_parts else "Config"
            label = f"{role['name']}<br/>{role['primary_lang']} | {role['loc']:,} LOC<br/>({resource_summary})"
            lines.append(f'    {role["node_id"]}["{label}"]')

        # Determine lifecycle flow based on shared modules and resource types
        # Repos that provision VPC come first (network foundation)
        # Repos with EMR/compute come next (build on the network)
        # Repos with CF bridge are an alternative path
        vpc_repos = [r for r in repo_roles if r["has_vpc"] and r["has_emr"]]
        cf_repos = [r for r in repo_roles if r["has_cf"]]
        emr_only = [r for r in repo_roles if r["has_emr"] and not r["has_cf"]]

        # Add shared infrastructure node
        lines.append('    AWS_Infra(("AWS Cloud<br/>Infrastructure"))')

        # Add connections from repos to AWS
        for role in repo_roles:
            if role["has_vpc"] or role["has_emr"] or role["has_cf"]:
                lines.append(f'    {role["node_id"]} -->|"provisions"| AWS_Infra')

        # Add cross-repo relationships
        # Find repos sharing the same module sources
        source_to_repos: dict[str, list] = defaultdict(list)
        for role in repo_roles:
            for mod_name in role["modules"]:
                source_to_repos[mod_name].append(role)

        seen_pairs = set()
        for source, repos in source_to_repos.items():
            if len(repos) > 1:
                for j in range(1, len(repos)):
                    pair = (repos[0]["idx"], repos[j]["idx"])
                    if pair not in seen_pairs:
                        seen_pairs.add(pair)
                        lines.append(
                            f'    {repos[0]["node_id"]} <-.->|"shared {source} module"| {repos[j]["node_id"]}'
                        )

        # Show alternative paths (CF repos offer alternative to direct TF)
        if cf_repos and emr_only:
            for cf in cf_repos:
                for emr in emr_only[:1]:
                    pair = (cf["idx"], emr["idx"])
                    if pair not in seen_pairs:
                        seen_pairs.add(pair)
                        lines.append(
                            f'    {cf["node_id"]} -.->|"alternative IaC approach"| {emr["node_id"]}'
                        )

        # Add runtime node (what the infrastructure enables)
        has_any_emr = any(r["has_emr"] for r in repo_roles)
        if has_any_emr:
            lines.append('    Runtime(("Runtime<br/>EMR Jobs &<br/>Data Processing"))')
            lines.append('    AWS_Infra -->|"enables"| Runtime')

        # Styling
        for sd in self._get_style_definitions():
            lines.append(f"    {sd}")

        for role in repo_roles:
            classification = self._classify_repo(self._parsed_repos[role["idx"]])
            class_map = {
                "iac": "iacNode", "service": "serviceNode",
                "event_processor": "serviceNode", "data": "dataNode", "library": "iacNode",
            }
            cls = class_map.get(classification, "iacNode")
            lines.append(f"    class {role['node_id']} {cls}")

        lines.append("    class AWS_Infra computeNode")
        if has_any_emr:
            lines.append("    class Runtime serviceNode")

        lines.append("```")
        return "\n".join(lines)

    def _extract_aws_service_nodes(self) -> list[dict]:
        """Extract distinct AWS service nodes from resource categories and VPC endpoints."""
        seen_ids = set()
        services = []

        # From resource categories across all repos
        for repo in self._parsed_repos:
            for cat in repo["resource_categories"]:
                if cat in _SERVICE_MAP:
                    svc = _SERVICE_MAP[cat]
                    if svc["id"] not in seen_ids:
                        seen_ids.add(svc["id"])
                        services.append(dict(svc))

            # From VPC endpoint names (aws_vpc_endpoint resources)
            for res in repo["terraform_resources"]:
                if res["type"] == "aws_vpc_endpoint":
                    ep_name = res["name"].lower()
                    for key, svc in _VPC_ENDPOINT_SERVICE_MAP.items():
                        if key in ep_name and svc["id"] not in seen_ids:
                            seen_ids.add(svc["id"])
                            services.append(dict(svc))

            # From CloudFormation resources
            for res in repo["terraform_resources"]:
                if "cloudformation" in res["type"]:
                    svc_id = "svc_CF"
                    if svc_id not in seen_ids:
                        seen_ids.add(svc_id)
                        services.append({
                            "id": svc_id,
                            "display": "CloudFormation\nStack Management",
                            "category": "compute",
                        })

        return services

    def _map_repo_to_services(self, repo: dict) -> list[tuple[str, str]]:
        """Map a repo to the AWS service IDs it provisions.

        Returns list of (service_id, edge_label) tuples.
        """
        edges = []
        seen = set()

        # Map from resource categories
        cat_to_label = {
            "Networking": ("svc_VPC", "provisions network"),
            "Compute/EMR": ("svc_EMR", "deploys cluster"),
            "Compute/EC2": ("svc_EC2", "deploys"),
            "Compute/Lambda": ("svc_Lambda", "deploys"),
            "Compute/ECS": ("svc_ECS", "deploys"),
            "IAM": ("svc_IAM", "configures"),
            "Security": ("svc_SG", "configures"),
            "Load Balancing": ("svc_ELB", "provisions"),
            "Storage/S3": ("svc_S3", "references"),
            "Storage/EBS": ("svc_EBS", "provisions"),
            "Database/RDS": ("svc_RDS", "provisions"),
            "Database/DynamoDB": ("svc_DynamoDB", "provisions"),
            "Monitoring": ("svc_CW", "configures"),
        }
        for cat in repo["resource_categories"]:
            if cat in cat_to_label:
                svc_id, label = cat_to_label[cat]
                if svc_id not in seen:
                    seen.add(svc_id)
                    edges.append((svc_id, label))

        # Infer from VPC endpoint names
        for res in repo["terraform_resources"]:
            if res["type"] == "aws_vpc_endpoint":
                ep_name = res["name"].lower()
                for key, svc in _VPC_ENDPOINT_SERVICE_MAP.items():
                    if key in ep_name and svc["id"] not in seen:
                        seen.add(svc["id"])
                        edges.append((svc["id"], "references"))

        # CloudFormation resources
        for res in repo["terraform_resources"]:
            if "cloudformation" in res["type"] and "svc_CF" not in seen:
                seen.add("svc_CF")
                edges.append(("svc_CF", "orchestrates"))

        return edges

    def _generate_overview_diagram(self) -> str:
        """Diagram 1: Repos grouped by type with connections and styling."""
        lines = ["```mermaid", "---", "title: Network/Architecture Overview — How Repos Connect to AWS Services", "---", "graph TD"]

        # Group repos by classification
        groups: dict[str, list[tuple[int, dict]]] = defaultdict(list)
        for i, repo in enumerate(self._parsed_repos):
            classification = self._classify_repo(repo)
            groups[classification].append((i, repo))

        subgraph_labels = {
            "iac": "Infrastructure as Code",
            "service": "Application Services",
            "event_processor": "Event Processors",
            "data": "Data Layer",
            "library": "Libraries",
        }

        # If all repos are the same type, use a single descriptive subgraph
        if len(groups) == 1:
            group_type = next(iter(groups))
            label = subgraph_labels.get(group_type, "Platform Overview")
            lines.append(f'    subgraph Platform["{label}"]')
            for i, repo in groups[group_type]:
                node_id = self._safe_id(repo["display_name"], i)
                node_label = (
                    f"{repo['display_name']}<br/>"
                    f"{repo['primary_language']} | {repo['total_loc']:,} LOC"
                )
                classification = self._classify_repo(repo)
                shape_cat = {"iac": "default", "service": "service", "data": "storage"}.get(
                    classification, "default"
                )
                lines.append(f'        {self._node_shape(node_id, node_label, shape_cat)}')
            lines.append("    end")
        else:
            for group_type in ("iac", "service", "event_processor", "data", "library"):
                if group_type not in groups:
                    continue
                repos = groups[group_type]
                label = subgraph_labels[group_type]
                sg_id = self._safe_subgraph_id(label)
                lines.append(f'    subgraph {sg_id}["{label}"]')
                for i, repo in repos:
                    node_id = self._safe_id(repo["display_name"], i)
                    node_label = (
                        f"{repo['display_name']}<br/>"
                        f"{repo['primary_language']} | {repo['total_loc']:,} LOC"
                    )
                    shape_cat = {"iac": "default", "service": "service", "data": "storage"}.get(
                        group_type, "default"
                    )
                    lines.append(f'        {self._node_shape(node_id, node_label, shape_cat)}')
                lines.append("    end")

        # Add AWS Cloud Services subgraph (if any resources exist)
        service_nodes = self._extract_aws_service_nodes()
        if service_nodes:
            lines.append('    subgraph AWSCloud["AWS Cloud Services"]')
            for svc in service_nodes:
                lines.append(f'        {self._node_shape(svc["id"], svc["display"], svc["category"])}')
            lines.append("    end")

            # Network Infrastructure subgraph (extract SG from AWSCloud for clarity)
            has_sg = any(s["id"] == "svc_SG" for s in service_nodes)
            has_vpc = any(s["id"] == "svc_VPC" for s in service_nodes)
            if has_sg and has_vpc:
                # The SG and VPC are already in AWSCloud, add structural edge
                pass

        # Add repo-to-service edges
        service_ids = {s["id"] for s in service_nodes}
        for i, repo in enumerate(self._parsed_repos):
            repo_node = self._safe_id(repo["display_name"], i)
            for svc_id, edge_label in self._map_repo_to_services(repo):
                if svc_id in service_ids:
                    lines.append(f'    {repo_node} -->|"{edge_label}"| {svc_id}')

        # Add service-to-service structural edges
        for from_svc, to_svc, label in _SERVICE_EDGES:
            if from_svc in service_ids and to_svc in service_ids:
                lines.append(f'    {from_svc} -->|"{label}"| {to_svc}')

        # Add inferred repo-to-repo connections
        connections = self._infer_repo_connections()
        for from_idx, to_idx, label, style in connections:
            from_id = self._safe_id(self._parsed_repos[from_idx]["display_name"], from_idx)
            to_id = self._safe_id(self._parsed_repos[to_idx]["display_name"], to_idx)
            if style == "dotted":
                lines.append(f'    {from_id} -.->|"{label}"| {to_id}')
            else:
                lines.append(f'    {from_id} -->|"{label}"| {to_id}')

        # Add styling
        style_defs = self._get_style_definitions()
        for sd in style_defs:
            lines.append(f"    {sd}")

        # Apply classes to repo nodes
        for i, repo in enumerate(self._parsed_repos):
            node_id = self._safe_id(repo["display_name"], i)
            classification = self._classify_repo(repo)
            class_map = {
                "iac": "iacNode",
                "service": "serviceNode",
                "event_processor": "serviceNode",
                "data": "dataNode",
                "library": "iacNode",
            }
            cls = class_map.get(classification, "iacNode")
            lines.append(f"    class {node_id} {cls}")

        # Apply classes to service nodes
        svc_class_map = {
            "storage": "dataNode",
            "compute": "computeNode",
            "security": "securityNode",
            "service": "serviceNode",
        }
        for svc in service_nodes:
            cls = svc_class_map.get(svc["category"], "iacNode")
            lines.append(f"    class {svc['id']} {cls}")

        lines.append("```")
        return "\n".join(lines)

    def _generate_tech_stack_diagram(self) -> str:
        """Diagram 2: Repos grouped by technology with styling."""
        # Build tech -> repos mapping
        tech_repos: dict[str, list[tuple[int, dict]]] = defaultdict(list)
        for i, repo in enumerate(self._parsed_repos):
            for tech in repo["tech_stack"]:
                tech_repos[tech].append((i, repo))

        if not tech_repos:
            return ""

        lines = ["```mermaid", "---", "title: Technology Stack", "---", "graph LR"]

        for tech in sorted(tech_repos.keys()):
            repos = tech_repos[tech]
            safe_tech = self._safe_subgraph_id(tech)
            lines.append(f'    subgraph {safe_tech}["{tech}"]')
            for idx, repo in repos:
                node_id = self._safe_id(repo["display_name"], idx)
                lines.append(f'        {node_id}["{repo["display_name"]}"]')
            lines.append("    end")

        # Add cross-tech edges for repos appearing in multiple groups
        repo_techs: dict[int, list[str]] = defaultdict(list)
        for tech, repos in tech_repos.items():
            for idx, _ in repos:
                repo_techs[idx].append(tech)

        edge_seen = set()
        for idx, techs in repo_techs.items():
            if len(techs) >= 2:
                node_id = self._safe_id(self._parsed_repos[idx]["display_name"], idx)
                sorted_techs = sorted(techs)
                for j in range(1, len(sorted_techs)):
                    key = (sorted_techs[0], sorted_techs[j], idx)
                    if key not in edge_seen:
                        edge_seen.add(key)
                        t1_sg = self._safe_subgraph_id(sorted_techs[0])
                        t2_sg = self._safe_subgraph_id(sorted_techs[j])
                        lines.append(f'    {t1_sg} -.->|"{self._parsed_repos[idx]["display_name"]}"| {t2_sg}')
                        break  # One edge per repo to avoid clutter

        # Apply styles to repo nodes
        for idx, repo in enumerate(self._parsed_repos):
            node_id = self._safe_id(repo["display_name"], idx)
            classification = self._classify_repo(repo)
            class_map = {
                "iac": "iacNode",
                "service": "serviceNode",
                "event_processor": "serviceNode",
                "data": "dataNode",
                "library": "iacNode",
            }
            cls = class_map.get(classification, "iacNode")
            lines.append(f"    class {node_id} {cls}")

        # Style definitions
        for sd in self._get_style_definitions():
            lines.append(f"    {sd}")

        lines.append("```")
        return "\n".join(lines)

    def _generate_infrastructure_diagram(self) -> str:
        """Diagram 3: Layered infrastructure architecture from Terraform resources."""
        # Collect all resources across repos
        all_resources: list[dict] = []
        all_categories: dict[str, int] = defaultdict(int)
        provisioning_repos: list[tuple[int, dict]] = []

        for i, repo in enumerate(self._parsed_repos):
            if repo["terraform_resources"]:
                provisioning_repos.append((i, repo))
                all_resources.extend(repo["terraform_resources"])
            for cat, count in repo["resource_categories"].items():
                all_categories[cat] += count

        if not all_resources:
            return ""

        # Group resources by architectural layer
        layers: dict[str, list[dict]] = defaultdict(list)
        for res in all_resources:
            layer = _LAYER_MAP.get(res["category"], "other")
            layers[layer].append(res)

        lines = ["```mermaid", "---", "title: Infrastructure Architecture — Layered Resource View", "---", "graph TD"]

        # Add repo nodes at the top
        if provisioning_repos:
            lines.append('    subgraph IaC["Infrastructure as Code"]')
            for idx, repo in provisioning_repos:
                node_id = self._safe_id(repo["display_name"], idx)
                lines.append(f'        {node_id}["{repo["display_name"]}<br/>{repo["primary_language"]}"]')
            lines.append("    end")

        layer_config = [
            ("compute", "Compute", "computeNode"),
            ("loadbalancing", "Load Balancing", "networkNode"),
            ("network", "Network", "networkNode"),
            ("storage", "Data & Storage", "dataNode"),
            ("security", "Security & IAM", "securityNode"),
            ("monitoring", "Monitoring", "computeNode"),
        ]

        # Deduplicate resource types within each layer for the diagram
        layer_node_ids: dict[str, list[str]] = defaultdict(list)

        for layer_key, layer_label, _style_class in layer_config:
            if layer_key not in layers:
                continue

            # Get unique resource types for this layer
            seen_types: dict[str, dict] = {}
            for res in layers[layer_key]:
                base_type = res["type"]
                if base_type not in seen_types:
                    seen_types[base_type] = res

            sg_id = f"layer_{layer_key}"
            lines.append(f'    subgraph {sg_id}["{layer_label}"]')

            for res_type, res in seen_types.items():
                # Strip aws_ prefix from both node ID and display for readability
                clean_type = res_type.replace("aws_", "")
                node_id = f"res_{re.sub(r'[^a-zA-Z0-9]', '_', clean_type)}"
                display = clean_type.replace("_", " ").title()
                cat = res["category"]

                # Pick node shape based on category
                if "Storage" in cat or "Database" in cat or "s3" in res_type:
                    node_str = self._node_shape(node_id, display, "storage")
                elif "Compute" in cat or "emr" in res_type or "instance" in res_type:
                    node_str = self._node_shape(node_id, display, "compute")
                elif "Security" in cat or "security_group" in res_type:
                    node_str = self._node_shape(node_id, display, "security")
                else:
                    node_str = f'{node_id}["{display}"]'

                lines.append(f'        {node_str}')
                layer_node_ids[layer_key].append(node_id)

            lines.append("    end")

        # Add structural edges between layers
        compute_nodes = layer_node_ids.get("compute", [])
        network_nodes = layer_node_ids.get("network", [])
        security_nodes = layer_node_ids.get("security", [])
        storage_nodes = layer_node_ids.get("storage", [])
        lb_nodes = layer_node_ids.get("loadbalancing", [])

        # Compute runs within network
        if compute_nodes and network_nodes:
            # Find VPC-like node
            vpc_node = next((n for n in network_nodes if "vpc" in n.lower()), network_nodes[0])
            for cn in compute_nodes:
                lines.append(f'    {cn} -->|"runs within"| {vpc_node}')

        # Compute uses IAM roles
        if compute_nodes and security_nodes:
            iam_node = next((n for n in security_nodes if "iam" in n.lower()), None)
            if iam_node:
                for cn in compute_nodes:
                    lines.append(f'    {cn} -->|"uses roles"| {iam_node}')

        # Load balancer routes to compute
        if lb_nodes and compute_nodes:
            for lbn in lb_nodes[:1]:
                lines.append(f'    {lbn} -->|"routes to"| {compute_nodes[0]}')

        # Security groups protect network
        if security_nodes and network_nodes:
            sg_node = next((n for n in security_nodes if "security_group" in n.lower()), None)
            subnet_node = next((n for n in network_nodes if "subnet" in n.lower()), None)
            if sg_node and subnet_node:
                lines.append(f'    {sg_node} -->|"protects"| {subnet_node}')

        # Repos provision layers (dotted lines)
        for idx, repo in provisioning_repos:
            repo_node = self._safe_id(repo["display_name"], idx)
            # Find which layers this repo provisions
            repo_layers = set()
            for res in repo["terraform_resources"]:
                layer = _LAYER_MAP.get(res["category"])
                if layer:
                    repo_layers.add(layer)
            for layer in repo_layers:
                if layer_node_ids.get(layer):
                    target = layer_node_ids[layer][0]
                    layer_label = layer.replace("_", " ")
                    lines.append(f'    {repo_node} -.->|"provisions"| {target}')

        # Add styling
        for sd in self._get_style_definitions():
            lines.append(f"    {sd}")

        # Apply styles to layer nodes
        style_map = {
            "compute": "computeNode",
            "loadbalancing": "networkNode",
            "network": "networkNode",
            "storage": "dataNode",
            "security": "securityNode",
            "monitoring": "computeNode",
        }
        for layer_key, node_ids in layer_node_ids.items():
            cls = style_map.get(layer_key, "iacNode")
            for nid in node_ids:
                lines.append(f"    class {nid} {cls}")

        # Style repo nodes
        for idx, repo in provisioning_repos:
            node_id = self._safe_id(repo["display_name"], idx)
            lines.append(f"    class {node_id} iacNode")

        lines.append("```")
        return "\n".join(lines)

    def _generate_data_flow_diagram(self) -> str:
        """Diagram: Comprehensive data flow showing infrastructure, security, and processing."""
        # Only generate for repos with terraform resources
        has_resources = any(r["terraform_resources"] for r in self._parsed_repos)
        if not has_resources:
            return ""

        # Collect all resource categories and features across repos
        all_categories = set()
        has_emr = False
        has_ec2 = False
        has_cf = False
        has_bastion = False
        has_s3 = False
        has_iam = False
        has_sg = False
        has_vpc = False
        has_lb = False

        for repo in self._parsed_repos:
            all_categories.update(repo["resource_categories"].keys())
            for mod in repo["module_chain"]:
                if "bastion" in mod["name"].lower():
                    has_bastion = True
            for res in repo["terraform_resources"]:
                if "cloudformation" in res["type"]:
                    has_cf = True
                if res["type"] == "aws_vpc_endpoint" and "s3" in res["name"].lower():
                    has_s3 = True

        has_emr = "Compute/EMR" in all_categories
        has_ec2 = "Compute/EC2" in all_categories
        has_iam = "IAM" in all_categories
        has_sg = "Security" in all_categories
        has_vpc = "Networking" in all_categories
        has_lb = "Load Balancing" in all_categories
        if "Storage/S3" in all_categories:
            has_s3 = True

        lines = ["```mermaid", "---", "title: Data Flow — End-to-End Infrastructure and Processing Pipeline", "---", "flowchart LR"]

        # Data Sources subgraph
        lines.append('    subgraph Sources["Data Sources"]')
        if has_emr:
            lines.append('        DataEngineers(("Data Engineers"))')
        lines.append('        ExternalData{{"External Data Sources"}}')
        lines.append("    end")

        # Infrastructure Control Plane
        lines.append('    subgraph ControlPlane["Infrastructure Control Plane"]')
        lines.append('        TerraformState[("Terraform State<br/>(S3 Backend)")]')
        if has_cf:
            lines.append('        CloudFormation{{"CloudFormation"}}')
        lines.append("    end")

        # Network Layer
        if has_vpc:
            lines.append('    subgraph NetworkLayer["Network Layer"]')
            lines.append('        VPC["VPC<br/>Network Boundary"]')
            lines.append('        PrivateSubnets["Private Subnets"]')
            lines.append('        PublicSubnets["Public Subnets"]')
            lines.append('        NAT["NAT Gateway"]')
            lines.append('        IGW["Internet Gateway"]')
            lines.append("    end")

        # Compute subgraph
        if has_emr or has_ec2:
            lines.append('    subgraph ComputeLayer["Compute Layer"]')
            if has_emr:
                lines.append('        EMRMaster["EMR Master Node"]')
                lines.append('        EMRCore["EMR Core Nodes<br/>(HDFS + Processing)"]')
                lines.append('        EMRTask["EMR Task Nodes"]')
            if has_ec2 and has_bastion:
                lines.append('        Bastion["Bastion Host"]')
            lines.append("    end")

        # Security subgraph
        if has_iam or has_sg:
            lines.append('    subgraph SecurityLayer["Security & Config"]')
            if has_iam:
                lines.append('        IAMRoles{{"IAM Roles & Policies"}}')
            if has_sg:
                lines.append('        SecurityGroups["Security Groups"]')
            lines.append("    end")

        # Data Persistence
        if has_s3 or has_emr:
            lines.append('    subgraph DataLayer["Data Persistence"]')
            if has_s3:
                lines.append('        S3DataLake[("S3 Data Lake")]')
                lines.append('        ProcessedData[("Processed Data<br/>(S3 Output)")]')
            if has_emr:
                lines.append('        HDFS[("HDFS<br/>Cluster Storage")]')
            lines.append("    end")

        # Monitoring
        lines.append('    subgraph Monitoring["Monitoring"]')
        lines.append('        CloudWatchLogs(["CloudWatch Logs"])')
        lines.append('        CloudWatchMetrics(["CloudWatch Metrics"])')
        lines.append("    end")

        # === Edges ===

        # Infrastructure provisioning flow
        if has_emr:
            lines.append('    DataEngineers -->|"terraform apply"| TerraformState')
        if has_cf:
            lines.append('    TerraformState -->|"state sync"| CloudFormation')
            if has_vpc:
                lines.append('    CloudFormation -.->|"provisions"| VPC')
            if has_emr:
                lines.append('    CloudFormation -.->|"provisions"| EMRMaster')

        # Network topology
        if has_vpc:
            lines.append("    VPC --> PrivateSubnets")
            lines.append("    VPC --> PublicSubnets")
            lines.append("    PublicSubnets --> IGW")
            lines.append("    PrivateSubnets --> NAT")
            lines.append("    NAT --> IGW")

        # Security configuration
        if has_iam and has_emr:
            lines.append('    IAMRoles -->|"access policies"| EMRMaster')
            lines.append('    IAMRoles -->|"access policies"| EMRCore')
        if has_sg and has_vpc:
            lines.append('    SecurityGroups -->|"network rules"| PrivateSubnets')

        # Data processing flow
        if has_s3 and has_emr:
            lines.append('    ExternalData -->|"raw data ingestion"| S3DataLake')
            lines.append('    S3DataLake -->|"input datasets"| EMRMaster')
            lines.append('    EMRMaster -->|"job distribution"| EMRCore')
            lines.append('    EMRMaster -->|"task distribution"| EMRTask')
            lines.append('    EMRCore <-->|"shuffle data"| HDFS')
            lines.append('    EMRTask -->|"processed results"| EMRCore')
            lines.append('    EMRCore -->|"final output"| ProcessedData')

        # User interaction flow
        if has_bastion and has_vpc:
            lines.append('    DataEngineers -->|"SSH via bastion"| PublicSubnets')
            if has_emr:
                lines.append('    PublicSubnets -->|"secure tunnel"| EMRMaster')
        if has_emr and not has_bastion:
            lines.append('    DataEngineers -->|"spark jobs"| EMRMaster')

        # Load balancer
        if has_lb and has_ec2:
            lines.append('    IGW -->|"incoming traffic"| PublicSubnets')

        # Monitoring flow (dotted)
        if has_emr:
            lines.append('    EMRMaster -.->|"application logs"| CloudWatchLogs')
            lines.append('    EMRCore -.->|"node metrics"| CloudWatchMetrics')
            lines.append('    EMRTask -.->|"task metrics"| CloudWatchMetrics')
        if has_vpc:
            lines.append('    VPC -.->|"VPC flow logs"| CloudWatchLogs')

        # Styling
        lines.append('    classDef storageNode fill:#cce5ff,stroke:#0066cc,stroke-width:2px')
        lines.append('    classDef processNode fill:#ccffcc,stroke:#006600,stroke-width:2px')
        lines.append('    classDef securityNode fill:#ffffcc,stroke:#cccc00,stroke-width:2px')
        lines.append('    classDef externalNode fill:#e6ccff,stroke:#6600cc,stroke-width:2px')

        # Apply styles
        if has_s3:
            lines.append("    class S3DataLake,ProcessedData,TerraformState storageNode")
        if has_emr:
            lines.append("    class HDFS storageNode")
            lines.append("    class EMRMaster,EMRCore,EMRTask processNode")
        if has_iam:
            lines.append("    class IAMRoles securityNode")
        if has_sg and has_vpc:
            lines.append("    class SecurityGroups,VPC securityNode")
        lines.append("    class ExternalData externalNode")
        if has_cf:
            lines.append("    class CloudFormation externalNode")

        lines.append("```")
        return "\n".join(lines)

    def _generate_module_diagrams(self) -> str:
        """Diagram 4: Per-repo module structure."""
        sections = []

        for i, repo in enumerate(self._parsed_repos):
            if not repo["modules"]:
                continue

            sections.append(f"### {repo['display_name']}")
            sections.append("")

            root_id = self._safe_id(repo["display_name"], i)
            title = f"Module Structure — {repo['display_name']}"
            lines = ["```mermaid", "---", f"title: {title}", "---", "graph TD"]
            lines.append(f'    {root_id}["{repo["display_name"]}"]')

            for j, mod in enumerate(repo["modules"]):
                mod_id = f"{root_id}_mod{j}"
                file_word = "file" if mod["files"] == 1 else "files"
                label = f"{mod['name']}/<br/>{mod['files']} {file_word}"
                lines.append(f'    {root_id} --> {mod_id}["{label}"]')

            lines.append("```")
            sections.append("\n".join(lines))
            sections.append("")

        return "\n".join(sections) if sections else ""

    def _generate_language_pie_chart(self) -> str:
        """Diagram 5: Aggregated language distribution pie chart."""
        agg: dict[str, int] = defaultdict(int)
        for repo in self._parsed_repos:
            for lang, loc in repo["languages"].items():
                agg[lang] += loc

        if not agg:
            return ""

        lines = ["```mermaid", 'pie title Language Distribution (LOC)']
        for lang in sorted(agg, key=lambda x: -agg[x]):
            lines.append(f'    "{lang}" : {agg[lang]}')
        lines.append("```")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Sequence Diagram Generation
    # ------------------------------------------------------------------

    def _generate_sequence_diagrams(self) -> str:
        """Generate Mermaid sequence diagrams from API, event, DB, and IaC data."""
        flows = []

        # Flow 1: API Request Flow
        api_flow = self._build_api_sequence_flow()
        if api_flow:
            flows.append(api_flow)

        # Flow 2: Event-Driven Flow
        event_flow = self._build_event_sequence_flow()
        if event_flow:
            flows.append(event_flow)

        # Flow 3: Shared Database Flow
        db_flow = self._build_shared_db_flow()
        if db_flow:
            flows.append(db_flow)

        # IaC Provisioning Flow (always add for IaC repos, not just as fallback)
        iac_flow = self._build_iac_provisioning_flow()
        if iac_flow:
            # If no service flows exist, IaC is primary; otherwise add after
            if not flows:
                flows.append(iac_flow)
            else:
                flows.append(iac_flow)

        # CloudFormation Integration Flow (conditional)
        cf_flow = self._build_cf_integration_flow()
        if cf_flow:
            flows.append(cf_flow)

        # Runtime/Operational Flow (conditional — EMR job submission)
        runtime_flow = self._build_runtime_sequence_flow()
        if runtime_flow:
            flows.append(runtime_flow)

        if not flows:
            return ""

        # Limit to 4 flows max
        flows = flows[:4]

        parts = []
        for i, (title, description, mermaid_lines) in enumerate(flows, 1):
            parts.append(f"### Flow {i}: {title}")
            parts.append("")
            parts.append(f"**Description:** {description}")
            parts.append("")
            parts.append("```mermaid")
            parts.append("---")
            parts.append(f"title: {title}")
            parts.append("---")
            parts.append("sequenceDiagram")
            parts.append("    autonumber")
            for line in mermaid_lines:
                parts.append(f"    {line}")
            parts.append("```")
            parts.append("")

        return "\n".join(parts)

    def _build_api_sequence_flow(self) -> tuple | None:
        """Build a sequence diagram for API request/response flows."""
        api_repos = [
            (i, r) for i, r in enumerate(self._parsed_repos)
            if r["api_endpoints"]
        ]
        if not api_repos:
            return None

        lines = []
        participants = []

        participants.append("participant Client")

        for idx, repo in api_repos[:3]:
            pid, display = self._safe_participant(repo["display_name"], idx)
            participants.append(f'participant {pid} as {display}')

        db_repos = [(i, r) for i, r in api_repos if r["databases"]]
        db_name = None
        if db_repos:
            db_name = db_repos[0][1]["databases"][0]
            safe_db = re.sub(r'[^a-zA-Z0-9]', '_', db_name)
            participants.append(f"participant {safe_db} as {db_name}")

        lines.extend(participants)

        for idx, repo in api_repos[:3]:
            pid, _ = self._safe_participant(repo["display_name"], idx)
            endpoints = sorted(
                repo["api_endpoints"],
                key=lambda e: (
                    0 if e["method"] in ("POST", "PUT") else
                    1 if e["method"] == "DELETE" else 2
                ),
            )[:3]

            for ep in endpoints:
                lines.append(f"Client->>{pid}: {ep['method']} {ep['path']}")
                lines.append(f"activate {pid}")
                if db_name and idx == api_repos[0][0]:
                    safe_db = re.sub(r'[^a-zA-Z0-9]', '_', db_name)
                    lines.append(f"Note over {pid}: Validate request")
                    lines.append(f"{pid}->>{safe_db}: persist data")
                    lines.append(f"{safe_db}-->>{pid}: OK")
                lines.append(f"{pid}-->>Client: response")
                lines.append(f"deactivate {pid}")

        return (
            "API Request Flow",
            "Request flow showing API endpoints and database interactions across services.",
            lines,
        )

    def _build_event_sequence_flow(self) -> tuple | None:
        """Build a sequence diagram for event-driven message flows."""
        event_repos = [
            (i, r) for i, r in enumerate(self._parsed_repos)
            if r["event_brokers"] or r["event_topics"]
        ]
        if not event_repos:
            return None

        topic_to_repos: dict[str, list[int]] = defaultdict(list)
        for idx, repo in event_repos:
            for topic in repo["event_topics"]:
                topic_to_repos[topic["name"]].append(idx)

        shared_topics = {t: repos for t, repos in topic_to_repos.items() if len(repos) > 1}

        all_brokers = set()
        for _, repo in event_repos:
            all_brokers.update(repo["event_brokers"])
        broker_name = sorted(all_brokers)[0] if all_brokers else "MessageBroker"

        lines = []
        participants = []

        if shared_topics:
            involved_indices = set()
            for repos in shared_topics.values():
                involved_indices.update(repos)

            for idx in sorted(involved_indices)[:4]:
                repo = self._parsed_repos[idx]
                pid, display = self._safe_participant(repo["display_name"], idx)
                participants.append(f'participant {pid} as {display}')

            safe_broker = re.sub(r'[^a-zA-Z0-9]', '_', broker_name)
            participants.append(f"participant {safe_broker} as {broker_name}")

            db_name = None
            for idx in sorted(involved_indices):
                if self._parsed_repos[idx]["databases"]:
                    db_name = self._parsed_repos[idx]["databases"][0]
                    break
            if db_name:
                safe_db = re.sub(r'[^a-zA-Z0-9]', '_', db_name)
                participants.append(f"participant {safe_db} as {db_name}")

            lines.extend(participants)
            lines.append(f"Note over {safe_broker}: Async message delivery")

            for topic_name in list(shared_topics.keys())[:3]:
                repo_indices = shared_topics[topic_name]
                pub_idx = repo_indices[0]
                pub_pid, _ = self._safe_participant(
                    self._parsed_repos[pub_idx]["display_name"], pub_idx
                )
                lines.append(f"{pub_pid}->>{safe_broker}: publish {topic_name}")

                for cons_idx in repo_indices[1:]:
                    cons_pid, _ = self._safe_participant(
                        self._parsed_repos[cons_idx]["display_name"], cons_idx
                    )
                    lines.append(f"{safe_broker}-->>{cons_pid}: consume {topic_name}")
                    lines.append(f"activate {cons_pid}")
                    if db_name and self._parsed_repos[cons_idx]["databases"]:
                        safe_db = re.sub(r'[^a-zA-Z0-9]', '_', db_name)
                        lines.append(f"{cons_pid}->>{safe_db}: update data")
                    lines.append(f"deactivate {cons_pid}")
        else:
            idx, repo = event_repos[0]
            pid, display = self._safe_participant(repo["display_name"], idx)
            safe_broker = re.sub(r'[^a-zA-Z0-9]', '_', broker_name)

            participants.append(f'participant {pid} as {display}')
            participants.append(f"participant {safe_broker} as {broker_name}")

            db_name = None
            if repo["databases"]:
                db_name = repo["databases"][0]
                safe_db = re.sub(r'[^a-zA-Z0-9]', '_', db_name)
                participants.append(f"participant {safe_db} as {db_name}")

            lines.extend(participants)
            lines.append(f"Note over {safe_broker}: Async message delivery")

            for topic in repo["event_topics"][:3]:
                lines.append(f"{pid}->>{safe_broker}: publish {topic['name']}")
                lines.append(f"{safe_broker}-->>{pid}: consume {topic['name']}")
                if db_name:
                    safe_db = re.sub(r'[^a-zA-Z0-9]', '_', db_name)
                    lines.append(f"{pid}->>{safe_db}: update data")

        description = (
            f"Asynchronous event flow via {broker_name}"
            + (" across multiple services." if shared_topics else " within a single service.")
        )

        return (
            "Event-Driven Message Flow",
            description,
            lines,
        )

    def _build_shared_db_flow(self) -> tuple | None:
        """Build a sequence diagram when multiple repos share a database type."""
        db_to_repos: dict[str, list[int]] = defaultdict(list)
        for i, repo in enumerate(self._parsed_repos):
            for db in repo["databases"]:
                db_to_repos[db].append(i)

        shared_dbs = {db: repos for db, repos in db_to_repos.items() if len(repos) > 1}
        if not shared_dbs:
            return None

        event_repos_set = {
            i for i, r in enumerate(self._parsed_repos)
            if r["event_brokers"] or r["event_topics"]
        }
        all_db_repos = set()
        for repos in shared_dbs.values():
            all_db_repos.update(repos)
        if all_db_repos.issubset(event_repos_set):
            return None

        lines = []
        participants = []

        db_name = sorted(shared_dbs.keys())[0]
        repo_indices = shared_dbs[db_name][:4]

        for idx in repo_indices:
            repo = self._parsed_repos[idx]
            pid, display = self._safe_participant(repo["display_name"], idx)
            participants.append(f'participant {pid} as {display}')

        safe_db = re.sub(r'[^a-zA-Z0-9]', '_', db_name)
        participants.append(f"participant {safe_db} as {db_name}")

        lines.extend(participants)

        for j, idx in enumerate(repo_indices):
            pid, _ = self._safe_participant(
                self._parsed_repos[idx]["display_name"], idx
            )
            if j == 0:
                lines.append(f"{pid}->>{safe_db}: write data")
                lines.append(f"activate {safe_db}")
                lines.append(f"{safe_db}-->>{pid}: OK")
                lines.append(f"deactivate {safe_db}")
            else:
                lines.append(f"{pid}->>{safe_db}: read data")
                lines.append(f"activate {safe_db}")
                lines.append(f"{safe_db}-->>{pid}: result set")
                lines.append(f"deactivate {safe_db}")

        return (
            "Shared Data Store Access",
            f"Multiple services accessing shared {db_name} database.",
            lines,
        )

    def _build_iac_provisioning_flow(self) -> tuple | None:
        """Build a rich sequence diagram for Terraform module provisioning."""
        iac_repos = [
            (i, r) for i, r in enumerate(self._parsed_repos)
            if r["module_chain"]
        ]
        if not iac_repos:
            return None

        lines = []
        participants = []

        # Determine cloud API participants from resource categories
        all_categories = set()
        for _, repo in iac_repos:
            all_categories.update(repo["resource_categories"].keys())

        # Add Operator/CI and Terraform participants
        participants.append("participant Op as Operator/CI Pipeline")
        participants.append("participant TF as Terraform")

        # Add state backend
        has_state = True  # Terraform always has state
        if has_state:
            participants.append("participant State as State Backend")

        # Map resource categories to cloud API participants
        api_participants: list[tuple[str, str]] = []
        cat_to_api = {
            "Networking": ("VPC_API", "AWS VPC API"),
            "Compute/EMR": ("EMR_API", "AWS EMR API"),
            "Compute/EC2": ("EC2_API", "AWS EC2 API"),
            "IAM": ("IAM_API", "AWS IAM API"),
            "Load Balancing": ("LB_API", "AWS ELB API"),
            "Security": ("SG_API", "AWS Security API"),
        }
        seen_apis = set()
        for cat in sorted(all_categories):
            if cat in cat_to_api and cat_to_api[cat][0] not in seen_apis:
                pid, display = cat_to_api[cat]
                api_participants.append((pid, display))
                seen_apis.add(pid)
                participants.append(f"participant {pid} as {display}")

        lines.extend(participants)

        # Opening: terraform plan/apply
        lines.append("Op->>TF: terraform plan/apply")
        lines.append("activate TF")

        # State management
        lines.append("TF->>State: Lock state file")
        lines.append("TF->>State: Read current state")
        lines.append("Note over TF: Calculate resource diff")

        # For each repo, show module provisioning with cloud API interactions
        for idx, repo in iac_repos[:2]:
            if len(iac_repos) > 1:
                lines.append(f"Note over TF: Provisioning {repo['display_name']}")

            for mod in repo["module_chain"][:6]:
                mod_name = mod["name"]
                mod_source = mod["source"].lstrip("./")

                # Determine which API this module likely calls based on module name
                target_api = None
                if "vpc" in mod_name.lower() or "network" in mod_name.lower():
                    target_api = "VPC_API"
                elif "emr" in mod_name.lower():
                    target_api = "EMR_API"
                elif "ec2" in mod_name.lower() or "instance" in mod_name.lower() or "bastion" in mod_name.lower():
                    target_api = "EC2_API"
                elif "iam" in mod_name.lower():
                    target_api = "IAM_API"
                elif "lb" in mod_name.lower() or "load" in mod_name.lower():
                    target_api = "LB_API"
                elif "security" in mod_name.lower() or "sg" in mod_name.lower():
                    target_api = "SG_API"

                # Only use target_api if it was added as a participant
                if target_api and target_api not in seen_apis:
                    target_api = None

                if target_api:
                    lines.append(f"TF->>{target_api}: Create {mod_name} resources")
                    lines.append(f"activate {target_api}")

                    # Find outputs for this module
                    mod_outputs = [
                        o for o in repo["outputs"]
                        if mod_source in o["file"]
                    ]
                    if mod_outputs:
                        output_names = ", ".join(o["name"] for o in mod_outputs[:3])
                        if len(mod_outputs) > 3:
                            output_names += f" +{len(mod_outputs) - 3} more"
                        lines.append(f"{target_api}-->>TF: {output_names}")
                    else:
                        lines.append(f"{target_api}-->>TF: Resource IDs")

                    lines.append(f"deactivate {target_api}")
                else:
                    # Fallback to the old style for modules we can't map
                    lines.append(f"Note over TF: Provision {mod_name} ({mod_source})")
                    mod_outputs = [
                        o for o in repo["outputs"]
                        if mod_source in o["file"]
                    ]
                    if mod_outputs:
                        output_names = ", ".join(o["name"] for o in mod_outputs[:3])
                        if len(mod_outputs) > 3:
                            output_names += f" +{len(mod_outputs) - 3} more"
                        lines.append(f"Note over TF: Outputs: {output_names}")

        # Add polling for compute resources (EMR, EC2)
        if "EMR_API" in seen_apis:
            lines.append("loop Poll until cluster ready")
            lines.append("TF->>EMR_API: Describe Cluster Status")
            lines.append("EMR_API-->>TF: Status (STARTING/WAITING)")
            lines.append("end")
            lines.append("Note right of EMR_API: Cluster bootstrapping ~5-15 min")

        # Close out
        lines.append("TF->>State: Update state file")
        lines.append("TF->>State: Release lock")
        lines.append("TF-->>Op: Apply complete")
        lines.append("deactivate TF")

        return (
            "Infrastructure Provisioning Sequence",
            "Terraform module provisioning order showing infrastructure dependency chain.",
            lines,
        )

    def _build_cf_integration_flow(self) -> tuple | None:
        """Build a sequence diagram for Terraform-CloudFormation integration."""
        # Detect repos with CloudFormation resources
        cf_repos = []
        for i, repo in enumerate(self._parsed_repos):
            for res in repo["terraform_resources"]:
                if "cloudformation" in res["type"]:
                    cf_repos.append((i, repo))
                    break

        if not cf_repos:
            return None

        # Check if EMR exists globally
        has_emr = any(
            "Compute/EMR" in r["resource_categories"]
            for r in self._parsed_repos
        )

        lines = []
        participants = [
            "participant Op as Operator",
            "participant TF as Terraform",
            "participant CF as AWS CloudFormation",
            "participant S3 as S3 Buckets",
        ]
        if has_emr:
            participants.append("participant EMR as AWS EMR")

        lines.extend(participants)

        lines.append("Op->>TF: terraform apply")
        lines.append("activate TF")

        # Upload CF template to S3
        lines.append("TF->>S3: Upload CF template to S3")
        lines.append("S3-->>TF: Template URL")

        # Create stack
        # Use real stack names from data if available
        stack_names = []
        for _, repo in cf_repos:
            for res in repo["terraform_resources"]:
                if "cloudformation" in res["type"]:
                    stack_names.append(res["name"])
        stack_label = stack_names[0] if stack_names else "EMR"

        lines.append(f"TF->>CF: Create/Update Stack ({stack_label} template)")
        lines.append("activate CF")
        lines.append("Note over CF: CloudFormation processes template")

        if has_emr:
            lines.append("CF->>EMR: Create EMR Cluster")
            lines.append("activate EMR")
        lines.append("CF->>S3: Create logging bucket")

        # Polling loop
        lines.append("loop Stack in progress")
        lines.append("TF->>CF: Describe Stack Status")
        lines.append("CF-->>TF: CREATE_IN_PROGRESS")
        lines.append("end")

        if has_emr:
            lines.append("EMR-->>CF: Cluster ready")
            lines.append("deactivate EMR")

        lines.append("CF-->>TF: CREATE_COMPLETE + Outputs")
        lines.append("deactivate CF")

        lines.append("Note over TF: Extract CF outputs<br/>(cluster ID, DNS, etc.)")
        lines.append("TF->>S3: Configure bucket policies<br/>using CF outputs")
        lines.append("TF-->>Op: Apply complete with outputs")
        lines.append("deactivate TF")

        return (
            "Terraform-CloudFormation Integration",
            "Hybrid IaC flow where Terraform orchestrates CloudFormation stack deployment.",
            lines,
        )

    def _build_runtime_sequence_flow(self) -> tuple | None:
        """Build a runtime/operational sequence for EMR job submission."""
        # Only generate if EMR resources exist
        has_emr = any(
            "Compute/EMR" in r["resource_categories"]
            for r in self._parsed_repos
        )
        if not has_emr:
            return None

        lines = []
        participants = [
            "participant User as Data Engineer",
            "participant CI as CI/CD Pipeline",
            "participant S3 as S3 (Scripts/Data)",
            "participant EMR as EMR Master Node",
            "participant YARN as YARN ResourceManager",
            "participant Workers as EMR Core/Task Nodes",
        ]

        lines.extend(participants)

        lines.append("User->>CI: Trigger job submission")
        lines.append("activate CI")

        lines.append("CI->>S3: Upload Spark application JAR/script")
        lines.append("S3-->>CI: s3://bucket/jobs/app.jar")

        lines.append("CI->>EMR: aws emr add-steps")
        lines.append('Note right of CI: Step: spark-submit<br/>--deploy-mode cluster')

        lines.append("EMR-->>CI: Step ID (PENDING)")

        lines.append("activate EMR")
        lines.append("EMR->>S3: Download application artifacts")
        lines.append("S3-->>EMR: JAR/Python files")

        lines.append("EMR->>YARN: Submit application")
        lines.append("activate YARN")

        lines.append("YARN->>Workers: Allocate containers")
        lines.append("activate Workers")

        lines.append("Workers->>S3: Read input data")
        lines.append("Note over Workers: Process data<br/>(map/reduce tasks)")
        lines.append("Workers->>S3: Write output data")
        lines.append("Workers-->>YARN: Tasks complete")
        lines.append("deactivate Workers")

        lines.append("YARN-->>EMR: Application SUCCESS")
        lines.append("deactivate YARN")

        lines.append("EMR-->>CI: Step COMPLETED")
        lines.append("deactivate EMR")

        lines.append("CI-->>User: Job finished successfully")
        lines.append("deactivate CI")

        # Error handling alt block
        lines.append("alt Job Failed")
        lines.append("EMR-->>CI: Step FAILED")
        lines.append("CI->>S3: Fetch logs for debugging")
        lines.append("CI-->>User: Job failed (logs attached)")
        lines.append("end")

        return (
            "EMR Job Submission",
            "Runtime data processing flow showing job submission through YARN orchestration.",
            lines,
        )

    # ------------------------------------------------------------------
    # Narrative Generation
    # ------------------------------------------------------------------

    def _generate_key_connections_narrative(self) -> str:
        """Generate narrative text about key architectural connections."""
        all_categories = set()
        has_cf = False
        has_s3 = False
        for repo in self._parsed_repos:
            all_categories.update(repo["resource_categories"].keys())
            for res in repo["terraform_resources"]:
                if "cloudformation" in res["type"]:
                    has_cf = True
                if res["type"] == "aws_vpc_endpoint" and "s3" in res["name"].lower():
                    has_s3 = True
        if "Storage/S3" in all_categories:
            has_s3 = True

        if not all_categories:
            return ""

        items = []
        count = 1

        # EMR as central target
        if "Compute/EMR" in all_categories:
            emr_repos = [r["display_name"] for r in self._parsed_repos if "Compute/EMR" in r["resource_categories"]]
            items.append(
                f"### {count}. **AWS EMR as Central Target Resource**\n"
                f"Repositories converge on provisioning AWS EMR clusters. "
                f"This represents the core purpose of this infrastructure — managing big data processing. "
                f"Repos involved: {', '.join(f'`{n}`' for n in emr_repos)}."
            )
            count += 1

        # Shared VPC
        vpc_repos = [r["display_name"] for r in self._parsed_repos if "Networking" in r["resource_categories"]]
        if len(vpc_repos) > 1:
            items.append(
                f"### {count}. **VPC/Network Foundation (Shared Concern)**\n"
                f"Multiple repositories handle VPC provisioning ({', '.join(f'`{n}`' for n in vpc_repos)}), "
                f"suggesting either different approaches to the same problem or a shared networking module pattern."
            )
            count += 1

        # TF-CF bridge
        if has_cf:
            items.append(
                f"### {count}. **Terraform-CloudFormation Bridge**\n"
                f"A hybrid IaC approach allows CloudFormation stacks to be managed within Terraform workflows. "
                f"This is a critical integration point for leveraging CloudFormation-specific features."
            )
            count += 1

        # S3 shared data layer
        if has_s3:
            items.append(
                f"### {count}. **S3 as Shared Data Layer**\n"
                f"EMR clusters require S3 for input data, output results, and logs. "
                f"S3 bucket configuration and access policies are a potential single point of failure."
            )
            count += 1

        # IAM security backbone
        if "IAM" in all_categories:
            items.append(
                f"### {count}. **IAM as Security Backbone**\n"
                f"All deployments require IAM roles and policies. "
                f"This is a critical security boundary if role permissions are incorrectly scoped."
            )
            count += 1

        if not items:
            return ""

        return "## Key Connections\n\n" + "\n\n".join(items)

    def _generate_data_flow_summary(self) -> str:
        """Generate data flow summary tables."""
        all_categories = set()
        has_s3 = False
        has_iam = False
        has_vpc = False
        has_emr = False

        for repo in self._parsed_repos:
            all_categories.update(repo["resource_categories"].keys())
            for res in repo["terraform_resources"]:
                if res["type"] == "aws_vpc_endpoint" and "s3" in res["name"].lower():
                    has_s3 = True

        has_emr = "Compute/EMR" in all_categories
        has_iam = "IAM" in all_categories
        has_vpc = "Networking" in all_categories
        if "Storage/S3" in all_categories:
            has_s3 = True

        if not all_categories:
            return ""

        rows = []
        if has_emr:
            rows.append("| **SSH Keys & Credentials** | Data Engineers | Bastion → EMR Master | Secrets Manager |")
        if has_iam:
            rows.append("| **IAM Access Keys** | AWS IAM | IAM Roles → Compute Nodes | AWS IAM (managed) |")
        rows.append("| **Terraform State** | Local → S3 | Contains resource IDs, ARNs | S3 Backend (encrypted) |")
        if has_vpc:
            rows.append("| **VPC Flow Logs** | Network Layer | VPC → CloudWatch | CloudWatch Logs |")
        if has_s3:
            rows.append("| **Application Data** | External Sources | S3 → EMR → S3 | S3 Data Lake |")

        table = (
            "## Data Flow Summary\n\n"
            "### Types of Sensitive Data Handled\n\n"
            "| Data Type | Source | Flow Path | Storage Location |\n"
            "|-----------|--------|-----------|------------------|\n"
            + "\n".join(rows)
        )
        return table

    def _generate_governance_concerns(self) -> str:
        """Generate data governance concerns based on detected patterns."""
        all_categories = set()
        has_emr = False
        has_vpc = False
        has_monitoring = False

        for repo in self._parsed_repos:
            all_categories.update(repo["resource_categories"].keys())

        has_emr = "Compute/EMR" in all_categories
        has_vpc = "Networking" in all_categories
        has_monitoring = "Monitoring" in all_categories

        if not all_categories:
            return ""

        concerns = []

        # Always for IaC repos
        concerns.append(
            "1. **Terraform State Exposure**\n"
            "   - State files may contain sensitive resource identifiers and outputs\n"
            "   - **Recommendation**: Enable S3 server-side encryption (SSE-KMS) and strict bucket policies"
        )

        if has_vpc:
            concerns.append(
                "2. **Cross-Boundary Data Movement**\n"
                "   - Data moves from public internet through NAT to private subnets\n"
                "   - **Recommendation**: Use VPC endpoints for S3 to avoid internet traversal"
            )

        if has_emr:
            concerns.append(
                f"{len(concerns) + 1}. **HDFS Encryption at Rest**\n"
                "   - Intermediate data on HDFS should be encrypted\n"
                "   - **Recommendation**: Enable HDFS transparent encryption with KMS integration"
            )

        if not has_monitoring:
            concerns.append(
                f"{len(concerns) + 1}. **CloudWatch Log Retention**\n"
                "   - Logs may contain sensitive job parameters or data samples\n"
                "   - **Recommendation**: Set appropriate retention policies and enable log group encryption"
            )

        if has_vpc:
            concerns.append(
                f"{len(concerns) + 1}. **Network Isolation**\n"
                "   - EMR clusters should be properly isolated in private subnets\n"
                "   - Security groups should limit ingress/egress appropriately"
            )

        return "### Potential Data Governance Concerns\n\n" + "\n\n".join(concerns)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _extract_section(self, content: str, section_name: str) -> str | None:
        """Extract the content of a specific H1 section from .arch.md content."""
        pattern = re.compile(r'^# ' + re.escape(section_name) + r'\s*$', re.MULTILINE)
        match = pattern.search(content)
        if not match:
            return None

        start = match.end()
        next_h1 = re.search(r'^# \w', content[start:], re.MULTILINE)
        if next_h1:
            section_text = content[start:start + next_h1.start()]
        else:
            section_text = content[start:]

        return section_text.strip()

    def _safe_participant(self, name: str, index: int) -> tuple:
        """Return (safe_id, display_name) for a sequence diagram participant."""
        safe = re.sub(r'[^a-zA-Z0-9]', '_', name)
        return f"p{index}_{safe}", name

    def _safe_id(self, name: str, index: int) -> str:
        """Generate a safe Mermaid node ID from a repo/module name."""
        safe = re.sub(r'[^a-zA-Z0-9]', '_', name)
        return f"repo{index}_{safe}"

    def _safe_subgraph_id(self, name: str) -> str:
        """Generate a safe Mermaid subgraph ID."""
        safe = re.sub(r'[^a-zA-Z0-9]', '_', name)
        return f"sg_{safe}"

    def _empty_document(self, generated_date: str | None = None) -> str:
        date_str = generated_date or datetime.now().strftime("%Y-%m-%d")
        return "\n".join([
            "# Cross-Repository Architecture Overview",
            "",
            "This document was automatically generated by RepoSwarm's static analysis.",
            f"Generated on: {date_str}",
            "",
            "---",
            "",
            "*No repository analysis data available for diagram generation.*",
            "",
            "---",
            "*Generated by static analysis (ENABLE_AI=false)*",
        ])
