"""
Static Analyzer -- no-AI replacement for ClaudeAnalyzer.

When ENABLE_AI=false, this class replaces Claude API calls with automated
static code analysis. It produces the same .arch.md output format (17 H1
sections) so that the downstream pipeline (cross-repo diagrams, Architecture
Hub, caching) works identically.

Each section is generated by scanning the repository's files using
language-specific parsers, regex patterns, and config file parsing.
"""

import logging
import os
from pathlib import Path
from typing import Dict, Optional

from .static_analyzers.language_detector import LanguageDetector
from .static_analyzers.terraform_parser import TerraformParser
from .static_analyzers.deployment_scanner import DeploymentScanner
from .static_analyzers.api_scanner import APIScanner
from .static_analyzers.entity_parser import EntityParser
from .static_analyzers.database_scanner import DatabaseScanner
from .static_analyzers.monitoring_scanner import MonitoringScanner
from .static_analyzers.feature_flag_scanner import FeatureFlagScanner
from .static_analyzers.data_mapping_scanner import DataMappingScanner
from .static_analyzers.security_scanner import SecurityScanner
from .static_analyzers.event_detector import EventDetector
from .static_analyzers.prompt_security_scanner import PromptSecurityScanner


class StaticAnalyzer:
    """Produces structured markdown analysis from code scanning -- no AI required."""

    def __init__(self, repo_path: str, logger=None):
        """
        Args:
            repo_path: Absolute path to the repository root directory.
            logger: Optional logger instance.
        """
        self.repo_path = repo_path
        self.logger = logger or logging.getLogger(__name__)
        self._language_detector = LanguageDetector(logger=self.logger)

        # Cached detection results (populated on first use)
        self._lang_result: Optional[dict] = None
        self._terraform_data: Optional[dict] = None
        self._deployment_data: Optional[dict] = None
        self._api_data: Optional[dict] = None
        self._entity_data: Optional[dict] = None
        self._database_data: Optional[dict] = None
        self._monitoring_data: Optional[dict] = None
        self._feature_flag_data: Optional[dict] = None
        self._data_mapping_data: Optional[dict] = None
        self._security_data: Optional[dict] = None
        self._event_data: Optional[dict] = None
        self._prompt_security_data: Optional[dict] = None

        # Dispatch table: step_name -> analyzer method
        self._section_analyzers = {
            "hl_overview": self._analyze_hl_overview,
            "module_deep_dive": self._analyze_module_deep_dive,
            "dependencies": self._analyze_dependencies,
            "core_entities": self._analyze_core_entities,
            "DBs": self._analyze_databases,
            "APIs": self._analyze_apis,
            "events": self._analyze_events,
            "service_dependencies": self._analyze_service_dependencies,
            "deployment": self._analyze_deployment,
            "authentication": self._analyze_authentication,
            "authorization": self._analyze_authorization,
            "data_mapping": self._analyze_data_mapping,
            "security_check": self._analyze_security_check,
            "monitoring": self._analyze_monitoring,
            "ml_services": self._analyze_ml_services,
            "feature_flags": self._analyze_feature_flags,
            "prompt_security_check": self._analyze_prompt_security_check,
            "resources": self._analyze_resources,
            "environments": self._analyze_environments,
        }

    def analyze_section(
        self,
        step_name: str,
        repo_structure: str,
        previous_context: Optional[str] = None,
        deps_data: Optional[dict] = None,
    ) -> str:
        """
        Run static analysis for a specific section.

        Args:
            step_name: Name of the analysis step (one of the 17 sections).
            repo_structure: Repository file tree string (from RepositoryAnalyzer).
            previous_context: Previous analysis sections (for context-dependent steps).
            deps_data: Parsed dependency data from read_dependencies_activity.

        Returns:
            Markdown string in the same format Claude would produce.
        """
        analyzer_fn = self._section_analyzers.get(step_name)
        if analyzer_fn is None:
            self.logger.warning(f"No static analyzer for section: {step_name}")
            return self._placeholder_section(step_name)

        try:
            result = analyzer_fn(repo_structure, previous_context, deps_data)
            self.logger.info(
                f"Static analysis for '{step_name}': {len(result)} chars"
            )
            return result
        except Exception as e:
            self.logger.error(f"Static analysis failed for '{step_name}': {e}")
            return self._error_section(step_name, str(e))

    @property
    def lang_result(self) -> dict:
        """Lazily compute and cache language detection results."""
        if self._lang_result is None:
            self._lang_result = self._language_detector.detect(self.repo_path)
        return self._lang_result

    # -------------------------------------------------------------------------
    # Section analyzers
    # -------------------------------------------------------------------------

    def _analyze_hl_overview(
        self, repo_structure: str, previous_context: str, deps_data: dict
    ) -> str:
        """High-level overview: languages, LOC, tech stack, directory structure."""
        result = self.lang_result
        repo_name = Path(self.repo_path).name

        # Try to read README for project purpose
        purpose = self._read_readme_summary()

        lines = []
        lines.append(f"**Repository Name:** {repo_name}")
        lines.append("")
        if purpose:
            lines.append(f"**Project Purpose:** {purpose}")
            lines.append("")

        # Language & tech stack from LanguageDetector
        lines.append(result and self._language_detector.format_as_markdown(result) or "")

        # Directory structure (already provided as repo_structure)
        lines.append("**Repository Structure:**")
        lines.append("")
        lines.append("```")
        # Truncate if very long
        struct_lines = repo_structure.split("\n")
        if len(struct_lines) > 80:
            lines.extend(struct_lines[:80])
            lines.append(f"... ({len(struct_lines) - 80} more lines)")
        else:
            lines.append(repo_structure)
        lines.append("```")
        lines.append("")

        lines.append("---")
        lines.append("*Generated by static analysis (ENABLE_AI=false)*")

        return "\n".join(lines)

    def _analyze_module_deep_dive(
        self, repo_structure: str, previous_context: str, deps_data: dict
    ) -> str:
        """Module/package structure analysis from directory tree."""
        repo = Path(self.repo_path)
        modules = []

        # Walk top-level directories as "modules"
        for item in sorted(repo.iterdir()):
            if not item.is_dir():
                continue
            if item.name.startswith(".") or item.name in LanguageDetector.SKIP_DIRS:
                continue

            file_count = sum(1 for _ in item.rglob("*") if _.is_file())
            dir_count = sum(1 for _ in item.rglob("*") if _.is_dir())

            # Detect sub-packages
            sub_packages = []
            for sub in sorted(item.iterdir()):
                if sub.is_dir() and not sub.name.startswith(".") and sub.name not in LanguageDetector.SKIP_DIRS:
                    sub_files = sum(1 for _ in sub.rglob("*") if _.is_file())
                    sub_packages.append(f"  - `{sub.name}/` ({sub_files} files)")

            modules.append({
                "name": item.name,
                "files": file_count,
                "dirs": dir_count,
                "sub_packages": sub_packages,
            })

        lines = []
        lines.append("**Module/Directory Breakdown:**")
        lines.append("")

        if not modules:
            lines.append("*No significant module structure detected.*")
        else:
            lines.append("| Module | Files | Subdirectories |")
            lines.append("|--------|------:|---------------:|")
            for mod in modules:
                lines.append(f"| `{mod['name']}/` | {mod['files']:,} | {mod['dirs']:,} |")
            lines.append("")

            # Detail sub-packages
            for mod in modules:
                if mod["sub_packages"]:
                    lines.append(f"**`{mod['name']}/`** sub-packages:")
                    lines.extend(mod["sub_packages"])
                    lines.append("")

        lines.append("---")
        lines.append("*Generated by static analysis (ENABLE_AI=false)*")

        return "\n".join(lines)

    def _analyze_dependencies(
        self, repo_structure: str, previous_context: str, deps_data: dict
    ) -> str:
        """Format dependency data. Reuses read_dependencies_activity output if available."""
        if deps_data:
            # deps_data is already formatted markdown from the existing activity
            return deps_data if isinstance(deps_data, str) else str(deps_data)

        # Fallback: just list dependency files found
        repo = Path(self.repo_path)
        dep_files = []
        patterns = [
            "pom.xml", "build.gradle", "build.gradle.kts",
            "package.json", "go.mod", "Cargo.toml", "Gemfile",
            "requirements*.txt", "pyproject.toml", "Pipfile",
            "composer.json", "*.csproj",
        ]

        for pattern in patterns:
            for match in repo.rglob(pattern):
                rel = match.relative_to(repo)
                dep_files.append(str(rel))

        lines = []
        if dep_files:
            lines.append("**Dependency Files Found:**")
            lines.append("")
            for f in sorted(dep_files):
                lines.append(f"- `{f}`")
        else:
            lines.append("*No standard dependency files detected.*")

        lines.append("")
        lines.append("---")
        lines.append("*Generated by static analysis (ENABLE_AI=false)*")

        return "\n".join(lines)

    # ---- Implemented section analyzers ----

    def _analyze_core_entities(self, repo_structure, previous_context, deps_data):
        data = self._get_entity_data()
        parser = EntityParser(self.repo_path)
        return parser.format_as_markdown(data)

    def _analyze_databases(self, repo_structure, previous_context, deps_data):
        data = self._get_database_data()
        scanner = DatabaseScanner(self.repo_path)
        return scanner.format_as_markdown(data)

    def _analyze_apis(self, repo_structure, previous_context, deps_data):
        data = self._get_api_data()
        scanner = APIScanner(self.repo_path)
        return scanner.format_as_markdown(data)

    def _analyze_events(self, repo_structure, previous_context, deps_data):
        data = self._get_event_data()
        detector = EventDetector(self.repo_path)
        return detector.format_as_markdown(data)

    def _analyze_service_dependencies(self, repo_structure, previous_context, deps_data):
        data = self._get_terraform_data()
        parser = TerraformParser(self.repo_path)
        return parser.format_service_dependencies(data)

    def _analyze_deployment(self, repo_structure, previous_context, deps_data):
        data = self._get_deployment_data()
        scanner = DeploymentScanner(self.repo_path)
        return scanner.format_as_markdown(data)

    def _analyze_authentication(self, repo_structure, previous_context, deps_data):
        data = self._get_security_data()
        scanner = SecurityScanner(self.repo_path)
        # Also merge Terraform IAM resources
        tf_data = self._get_terraform_data()
        iam_resources = [r for r in tf_data.get("resources", [])
                        if "iam" in r["type"].lower() or "cognito" in r["type"].lower()]
        md = scanner.format_authentication(data)
        if iam_resources and "No authentication" in md:
            # Fall back to Terraform IAM view
            lines = ["**Authentication/IAM Resources (Terraform):**\n"]
            lines.append("| Resource Type | Name | File |")
            lines.append("|--------------|------|------|")
            for r in sorted(iam_resources, key=lambda x: x["type"]):
                lines.append(f"| `{r['type']}` | {r['name']} | {r['file']} |")
            lines.append("\n---")
            lines.append("*Generated by static analysis (ENABLE_AI=false)*")
            return "\n".join(lines)
        if iam_resources and "No authentication" not in md:
            # Append Terraform IAM section
            lines = [md.rsplit("---", 1)[0].rstrip()]
            lines.append("\n**Terraform IAM Resources:**\n")
            lines.append("| Resource Type | Name | File |")
            lines.append("|--------------|------|------|")
            for r in sorted(iam_resources, key=lambda x: x["type"]):
                lines.append(f"| `{r['type']}` | {r['name']} | {r['file']} |")
            lines.append("\n---")
            lines.append("*Generated by static analysis (ENABLE_AI=false)*")
            return "\n".join(lines)
        return md

    def _analyze_authorization(self, repo_structure, previous_context, deps_data):
        data = self._get_security_data()
        scanner = SecurityScanner(self.repo_path)
        # Also merge Terraform authz resources
        tf_data = self._get_terraform_data()
        auth_resources = [r for r in tf_data.get("resources", [])
                         if any(kw in r["type"].lower() for kw in
                                ("security_group", "iam_policy", "iam_role_policy", "waf", "acl"))]
        md = scanner.format_authorization(data)
        if auth_resources and "No authorization" in md:
            lines = ["**Authorization/Access Control Resources (Terraform):**\n"]
            lines.append("| Resource Type | Name | Category | File |")
            lines.append("|--------------|------|----------|------|")
            for r in sorted(auth_resources, key=lambda x: x["type"]):
                lines.append(f"| `{r['type']}` | {r['name']} | {r['category']} | {r['file']} |")
            lines.append("\n---")
            lines.append("*Generated by static analysis (ENABLE_AI=false)*")
            return "\n".join(lines)
        if auth_resources and "No authorization" not in md:
            lines = [md.rsplit("---", 1)[0].rstrip()]
            lines.append("\n**Terraform Access Control Resources:**\n")
            lines.append("| Resource Type | Name | Category | File |")
            lines.append("|--------------|------|----------|------|")
            for r in sorted(auth_resources, key=lambda x: x["type"]):
                lines.append(f"| `{r['type']}` | {r['name']} | {r['category']} | {r['file']} |")
            lines.append("\n---")
            lines.append("*Generated by static analysis (ENABLE_AI=false)*")
            return "\n".join(lines)
        return md

    def _analyze_data_mapping(self, repo_structure, previous_context, deps_data):
        data = self._get_data_mapping_data()
        scanner = DataMappingScanner(self.repo_path)
        return scanner.format_as_markdown(data)

    def _analyze_security_check(self, repo_structure, previous_context, deps_data):
        data = self._get_security_data()
        scanner = SecurityScanner(self.repo_path)
        return scanner.format_security_check(data)

    def _analyze_monitoring(self, repo_structure, previous_context, deps_data):
        data = self._get_monitoring_data()
        scanner = MonitoringScanner(self.repo_path)
        return scanner.format_as_markdown(data)

    def _analyze_ml_services(self, repo_structure, previous_context, deps_data):
        # Check Terraform for ML-related resources
        tf_data = self._get_terraform_data()
        ml_resources = [r for r in tf_data.get("resources", [])
                       if any(kw in r["type"] for kw in ("sagemaker", "bedrock", "comprehend", "rekognition", "textract"))]
        # Also check for LLM/ML SDK imports from prompt security scanner
        prompt_data = self._get_prompt_security_data()
        llm_sdks = prompt_data.get("llm_sdks", [])

        if not ml_resources and not llm_sdks:
            return ("*No ML/AI service resources or SDK imports detected.*\n\n"
                    "---\n*Generated by static analysis (ENABLE_AI=false)*")

        lines = []

        if ml_resources:
            lines.append("**ML/AI Service Resources (Terraform):**\n")
            lines.append("| Resource Type | Name | File |")
            lines.append("|--------------|------|------|")
            for r in sorted(ml_resources, key=lambda x: x["type"]):
                lines.append(f"| `{r['type']}` | {r['name']} | {r['file']} |")
            lines.append("")

        if llm_sdks:
            lines.append("**LLM/AI SDK Usage Detected:**\n")
            lines.append("| SDK/Provider | File |")
            lines.append("|-------------|------|")
            for s in sorted(llm_sdks, key=lambda x: x["sdk"]):
                lines.append(f"| {s['sdk']} | `{s['file']}` |")

        lines.append("\n---")
        lines.append("*Generated by static analysis (ENABLE_AI=false)*")
        return "\n".join(lines)

    def _analyze_feature_flags(self, repo_structure, previous_context, deps_data):
        data = self._get_feature_flag_data()
        scanner = FeatureFlagScanner(self.repo_path)
        return scanner.format_as_markdown(data)

    def _analyze_prompt_security_check(self, repo_structure, previous_context, deps_data):
        data = self._get_prompt_security_data()
        scanner = PromptSecurityScanner(self.repo_path)
        return scanner.format_as_markdown(data)

    def _analyze_resources(self, repo_structure, previous_context, deps_data):
        data = self._get_terraform_data()
        parser = TerraformParser(self.repo_path)
        return parser.format_resources(data)

    def _analyze_environments(self, repo_structure, previous_context, deps_data):
        data = self._get_terraform_data()
        parser = TerraformParser(self.repo_path)
        return parser.format_environments(data)

    # ---- Lazy-cached parser data ----

    def _get_terraform_data(self) -> dict:
        if self._terraform_data is None:
            self._terraform_data = TerraformParser(self.repo_path).parse()
        return self._terraform_data

    def _get_deployment_data(self) -> dict:
        if self._deployment_data is None:
            self._deployment_data = DeploymentScanner(self.repo_path).scan()
        return self._deployment_data

    def _get_api_data(self) -> dict:
        if self._api_data is None:
            self._api_data = APIScanner(self.repo_path).scan()
        return self._api_data

    def _get_entity_data(self) -> dict:
        if self._entity_data is None:
            self._entity_data = EntityParser(self.repo_path).parse()
        return self._entity_data

    def _get_database_data(self) -> dict:
        if self._database_data is None:
            self._database_data = DatabaseScanner(self.repo_path).scan()
        return self._database_data

    def _get_monitoring_data(self) -> dict:
        if self._monitoring_data is None:
            self._monitoring_data = MonitoringScanner(self.repo_path).scan()
        return self._monitoring_data

    def _get_feature_flag_data(self) -> dict:
        if self._feature_flag_data is None:
            self._feature_flag_data = FeatureFlagScanner(self.repo_path).scan()
        return self._feature_flag_data

    def _get_data_mapping_data(self) -> dict:
        if self._data_mapping_data is None:
            self._data_mapping_data = DataMappingScanner(self.repo_path).scan()
        return self._data_mapping_data

    def _get_security_data(self) -> dict:
        if self._security_data is None:
            self._security_data = SecurityScanner(self.repo_path).scan()
        return self._security_data

    def _get_event_data(self) -> dict:
        if self._event_data is None:
            self._event_data = EventDetector(self.repo_path).scan()
        return self._event_data

    def _get_prompt_security_data(self) -> dict:
        if self._prompt_security_data is None:
            self._prompt_security_data = PromptSecurityScanner(self.repo_path).scan()
        return self._prompt_security_data

    # ---- Helpers ----

    def _read_readme_summary(self) -> str:
        """Read first paragraph of README for project purpose."""
        repo = Path(self.repo_path)
        for readme_name in ["README.md", "README.rst", "README.txt", "README"]:
            readme = repo / readme_name
            if readme.is_file():
                try:
                    content = readme.read_text(encoding="utf-8", errors="ignore")
                    # Extract first non-heading, non-blank paragraph
                    for line in content.split("\n"):
                        stripped = line.strip()
                        if not stripped:
                            continue
                        if stripped.startswith("#") or stripped.startswith("="):
                            continue
                        if stripped.startswith("![") or stripped.startswith("[!"):
                            continue  # badges
                        # Return first real text line (truncated)
                        if len(stripped) > 300:
                            return stripped[:300] + "..."
                        return stripped
                except (OSError, UnicodeDecodeError):
                    pass
        return ""

    def _placeholder_section(self, step_name: str) -> str:
        """Return a placeholder for sections not yet implemented."""
        return (
            f"*Static analysis for `{step_name}` is not yet implemented. "
            f"This section will be populated in a future update.*\n\n"
            f"---\n"
            f"*Generated by static analysis (ENABLE_AI=false)*"
        )

    def _error_section(self, step_name: str, error: str) -> str:
        """Return an error section when analysis fails."""
        return (
            f"*Static analysis for `{step_name}` encountered an error: {error}*\n\n"
            f"---\n"
            f"*Generated by static analysis (ENABLE_AI=false)*"
        )
