"""
Unit tests for StaticAnalyzer -- the no-AI replacement for ClaudeAnalyzer.
"""

import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import MagicMock

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'src'))

from investigator.core.static_analyzer import StaticAnalyzer


# Path to the sample_repo fixture
FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"
SAMPLE_REPO = FIXTURES_DIR / "sample_repo"

# A minimal repo_structure string for tests
SAMPLE_STRUCTURE = """\
sample_repo/
  README.md
  pom.xml
  Dockerfile
  go.mod
  src/
    main/
      java/
        com/
          example/
            Application.java
            UserController.java
  pkg/
    handler/
      main.go
  scripts/
    deploy.sh
  .github/
    workflows/
      ci.yml
"""


class TestStaticAnalyzerInit(unittest.TestCase):
    """Tests for StaticAnalyzer initialization."""

    def test_creates_with_repo_path(self):
        """StaticAnalyzer can be instantiated with a repo path."""
        analyzer = StaticAnalyzer(str(SAMPLE_REPO))
        self.assertEqual(analyzer.repo_path, str(SAMPLE_REPO))

    def test_creates_with_custom_logger(self):
        """StaticAnalyzer accepts a custom logger."""
        logger = MagicMock()
        analyzer = StaticAnalyzer(str(SAMPLE_REPO), logger=logger)
        self.assertEqual(analyzer.logger, logger)

    def test_section_dispatch_table_has_19_entries(self):
        """The dispatch table should map all 19 analysis sections (17 original + resources + environments)."""
        analyzer = StaticAnalyzer(str(SAMPLE_REPO))
        self.assertEqual(len(analyzer._section_analyzers), 19)


class TestStaticAnalyzerHlOverview(unittest.TestCase):
    """Tests for the hl_overview section."""

    @classmethod
    def setUpClass(cls):
        cls.analyzer = StaticAnalyzer(str(SAMPLE_REPO))
        cls.result = cls.analyzer.analyze_section(
            "hl_overview",
            SAMPLE_STRUCTURE,
        )

    def test_returns_non_empty_string(self):
        """hl_overview returns a non-empty markdown string."""
        self.assertIsInstance(self.result, str)
        self.assertGreater(len(self.result), 0)

    def test_contains_repo_name(self):
        """hl_overview includes the repository name."""
        self.assertIn("sample_repo", self.result)

    def test_contains_primary_language(self):
        """hl_overview includes a primary language line."""
        self.assertIn("**Primary Language:**", self.result)

    def test_contains_tech_stack(self):
        """hl_overview includes tech stack information."""
        self.assertIn("**Technology Stack:**", self.result)

    def test_contains_language_table(self):
        """hl_overview includes a language breakdown table."""
        self.assertIn("| Language |", self.result)

    def test_contains_repo_structure(self):
        """hl_overview includes the repository structure."""
        self.assertIn("**Repository Structure:**", self.result)
        self.assertIn("```", self.result)

    def test_contains_static_analysis_footer(self):
        """hl_overview ends with the static analysis generated-by footer."""
        self.assertIn("*Generated by static analysis (ENABLE_AI=false)*", self.result)

    def test_contains_readme_summary(self):
        """hl_overview extracts purpose from README."""
        self.assertIn("**Project Purpose:**", self.result)
        self.assertIn("sample repository", self.result)


class TestStaticAnalyzerModuleDeepDive(unittest.TestCase):
    """Tests for the module_deep_dive section."""

    @classmethod
    def setUpClass(cls):
        cls.analyzer = StaticAnalyzer(str(SAMPLE_REPO))
        cls.result = cls.analyzer.analyze_section(
            "module_deep_dive",
            SAMPLE_STRUCTURE,
        )

    def test_returns_non_empty_string(self):
        """module_deep_dive returns a non-empty markdown string."""
        self.assertIsInstance(self.result, str)
        self.assertGreater(len(self.result), 0)

    def test_contains_module_table(self):
        """module_deep_dive includes a module table."""
        self.assertIn("| Module |", self.result)

    def test_detects_src_directory(self):
        """module_deep_dive lists the src/ directory."""
        self.assertIn("`src/`", self.result)

    def test_detects_pkg_directory(self):
        """module_deep_dive lists the pkg/ directory."""
        self.assertIn("`pkg/`", self.result)

    def test_contains_static_analysis_footer(self):
        """module_deep_dive has the generated-by footer."""
        self.assertIn("*Generated by static analysis (ENABLE_AI=false)*", self.result)


class TestStaticAnalyzerDependencies(unittest.TestCase):
    """Tests for the dependencies section."""

    @classmethod
    def setUpClass(cls):
        cls.analyzer = StaticAnalyzer(str(SAMPLE_REPO))

    def test_with_deps_data_returns_it(self):
        """When deps_data is provided, it's used directly."""
        deps_md = "| Dependency | Version |\n|---|---|\n| spring-boot | 3.0 |"
        result = self.analyzer.analyze_section(
            "dependencies",
            SAMPLE_STRUCTURE,
            deps_data=deps_md,
        )
        self.assertIn("spring-boot", result)

    def test_without_deps_data_scans_files(self):
        """When no deps_data, fallback scans for dependency files."""
        result = self.analyzer.analyze_section(
            "dependencies",
            SAMPLE_STRUCTURE,
            deps_data=None,
        )
        self.assertIn("pom.xml", result)
        self.assertIn("go.mod", result)

    def test_contains_static_analysis_footer(self):
        """dependencies has the generated-by footer."""
        result = self.analyzer.analyze_section(
            "dependencies",
            SAMPLE_STRUCTURE,
        )
        self.assertIn("*Generated by static analysis (ENABLE_AI=false)*", result)


class TestStaticAnalyzerImplementedSections(unittest.TestCase):
    """Tests for sections that now have real implementations."""

    @classmethod
    def setUpClass(cls):
        cls.analyzer = StaticAnalyzer(str(SAMPLE_REPO))
        cls.implemented_sections = [
            "core_entities",
            "DBs",
            "APIs",
            "events",
            "service_dependencies",
            "deployment",
            "authentication",
            "authorization",
            "data_mapping",
            "security_check",
            "monitoring",
            "ml_services",
            "feature_flags",
            "prompt_security_check",
            "resources",
            "environments",
        ]

    def test_all_implemented_sections_return_strings(self):
        """Every implemented section returns a non-empty string."""
        for section in self.implemented_sections:
            result = self.analyzer.analyze_section(section, SAMPLE_STRUCTURE)
            self.assertIsInstance(result, str, f"Section {section} should return str")
            self.assertGreater(len(result), 0, f"Section {section} should be non-empty")

    def test_implemented_sections_have_footer(self):
        """Implemented sections have the static analysis footer."""
        for section in self.implemented_sections:
            result = self.analyzer.analyze_section(section, SAMPLE_STRUCTURE)
            self.assertIn("*Generated by static analysis (ENABLE_AI=false)*", result)


class TestStaticAnalyzerUnknownSection(unittest.TestCase):
    """Tests for unknown/invalid section names."""

    def setUp(self):
        self.analyzer = StaticAnalyzer(str(SAMPLE_REPO))

    def test_unknown_section_returns_placeholder(self):
        """An unrecognized section name returns a placeholder (not an exception)."""
        result = self.analyzer.analyze_section("totally_unknown_section", SAMPLE_STRUCTURE)
        self.assertIsInstance(result, str)
        self.assertIn("not yet implemented", result)


class TestStaticAnalyzerWithTempRepo(unittest.TestCase):
    """Tests using a temporary repo to control exact file contents."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.analyzer = StaticAnalyzer(self.tmpdir)

    def tearDown(self):
        import shutil
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def _write_file(self, name, content):
        filepath = Path(self.tmpdir) / name
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(content, encoding="utf-8")

    def test_hl_overview_no_readme(self):
        """hl_overview works when there is no README file."""
        self._write_file("main.py", "print('hello')")
        result = self.analyzer.analyze_section("hl_overview", "main.py")
        self.assertIsInstance(result, str)
        self.assertNotIn("**Project Purpose:**", result)

    def test_hl_overview_long_structure_truncated(self):
        """hl_overview truncates very long repo structures."""
        long_structure = "\n".join([f"file_{i}.py" for i in range(200)])
        self._write_file("main.py", "x = 1")
        result = self.analyzer.analyze_section("hl_overview", long_structure)
        self.assertIn("more lines", result)

    def test_module_deep_dive_empty_repo(self):
        """module_deep_dive handles a repo with no subdirectories."""
        self._write_file("main.py", "x = 1")
        result = self.analyzer.analyze_section("module_deep_dive", "main.py")
        self.assertIn("No significant module structure detected", result)

    def test_dependencies_no_dep_files(self):
        """dependencies handles a repo with no standard dependency files."""
        self._write_file("main.py", "x = 1")
        result = self.analyzer.analyze_section("dependencies", "main.py", deps_data=None)
        self.assertIn("No standard dependency files detected", result)


class TestStaticAnalyzerErrorHandling(unittest.TestCase):
    """Tests for error handling in analyze_section."""

    def test_analyzer_error_returns_error_section(self):
        """If a section analyzer raises, an error section is returned instead of crashing."""
        analyzer = StaticAnalyzer(str(SAMPLE_REPO))

        # Monkey-patch an analyzer to raise
        def _bad_analyzer(*args):
            raise ValueError("test explosion")

        analyzer._section_analyzers["hl_overview"] = _bad_analyzer

        result = analyzer.analyze_section("hl_overview", SAMPLE_STRUCTURE)
        self.assertIn("encountered an error", result)
        self.assertIn("test explosion", result)


class TestStaticAnalyzerLangResultCaching(unittest.TestCase):
    """Tests for lazy language detection caching."""

    def test_lang_result_cached(self):
        """Accessing lang_result twice returns the same object (cached)."""
        analyzer = StaticAnalyzer(str(SAMPLE_REPO))
        result1 = analyzer.lang_result
        result2 = analyzer.lang_result
        self.assertIs(result1, result2)

    def test_lang_result_is_dict(self):
        """lang_result returns a dict with expected structure."""
        analyzer = StaticAnalyzer(str(SAMPLE_REPO))
        result = analyzer.lang_result
        self.assertIsInstance(result, dict)
        self.assertIn("languages", result)
        self.assertIn("primary_language", result)


if __name__ == "__main__":
    unittest.main()
