"""
Unit tests for MermaidDiagramGenerator -- programmatic Mermaid diagram generation
from .arch.md static analysis data.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'src'))

from investigator.core.mermaid_diagram_generator import MermaidDiagramGenerator


# Realistic .arch.md content (matches real output format)
SAMPLE_ARCH_CONTENT_1 = """\
# hl_overview

High level overview of the codebase

**Repository Name:** aws-terraform-emr-network

**Primary Language:** Terraform
**Total Files:** 18
**Total Lines of Code:** 627

**Technology Stack:**
- Terraform
- Docker

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| Terraform | 11 | 626 | 163 | 106 |
| Shell | 1 | 1 | 0 | 1 |

---
*Generated by static analysis (ENABLE_AI=false)*

# module_deep_dive

Deep dive into modules

**Module/Directory Breakdown:**

| Module | Files | Subdirectories |
|--------|------:|---------------:|
| `arch-docs/` | 1 | 0 |
| `bastion/` | 3 | 0 |
| `emr/` | 5 | 0 |
| `vpc/` | 4 | 0 |

---
*Generated by static analysis (ENABLE_AI=false)*
"""

SAMPLE_ARCH_CONTENT_2 = """\
# hl_overview

High level overview of the codebase

**Repository Name:** backend-api

**Primary Language:** Java
**Total Files:** 120
**Total Lines of Code:** 8500

**Technology Stack:**
- Maven
- Docker
- Spring Boot
- Terraform

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| Java | 95 | 7200 | 1200 | 800 |
| YAML | 15 | 800 | 50 | 20 |
| Terraform | 5 | 300 | 50 | 30 |
| Shell | 5 | 200 | 20 | 10 |

---
*Generated by static analysis (ENABLE_AI=false)*

# module_deep_dive

Deep dive into modules

**Module/Directory Breakdown:**

| Module | Files | Subdirectories |
|--------|------:|---------------:|
| `src/main/java/` | 80 | 5 |
| `src/test/java/` | 30 | 3 |
| `terraform/` | 5 | 1 |
| `scripts/` | 5 | 0 |

---
*Generated by static analysis (ENABLE_AI=false)*
"""


# --- Fixtures for sequence diagram testing ---

SAMPLE_ARCH_API_SERVICE = """\
# hl_overview

High level overview of the codebase

**Repository Name:** order-service

**Primary Language:** Java
**Total Files:** 50
**Total Lines of Code:** 4000

**Technology Stack:**
- Spring Boot
- Maven
- Docker

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| Java | 45 | 3500 | 400 | 300 |
| YAML | 5 | 500 | 30 | 10 |

---
*Generated by static analysis (ENABLE_AI=false)*

# module_deep_dive

Deep dive into modules

**Module/Directory Breakdown:**

| Module | Files | Subdirectories |
|--------|------:|---------------:|
| `src/main/java/` | 40 | 4 |
| `src/test/java/` | 10 | 2 |

---
*Generated by static analysis (ENABLE_AI=false)*

# APIs

APIs analysis

**Route Endpoints (from code):**

| Method | Path | File |
|--------|------|------|
| POST | `/api/orders` | OrderController.java |
| GET | `/api/orders/{id}` | OrderController.java |
| PUT | `/api/orders/{id}/status` | OrderController.java |

---
*Generated by static analysis (ENABLE_AI=false)*

# events

events analysis

**Event/Messaging Systems Detected:**

- **Kafka**
  - Code: `OrderProducer.java`

**Topics/Queues:**

| Name | Type | File |
|------|------|------|
| `order.created` | Kafka topic (producer) | `OrderProducer.java` |
| `order.shipped` | Kafka topic (consumer) | `ShipListener.java` |

---
*Generated by static analysis (ENABLE_AI=false)*

# DBs

databases analysis

**Connection Strings Detected:**

| Database Type | Config File |
|--------------|-------------|
| PostgreSQL | `application.yml` |

---
*Generated by static analysis (ENABLE_AI=false)*

# service_dependencies

Analyze service dependencies

*No module or provider dependencies found.*

---
*Generated by static analysis (ENABLE_AI=false)*
"""

SAMPLE_ARCH_SHIPPING_SERVICE = """\
# hl_overview

High level overview of the codebase

**Repository Name:** shipping-service

**Primary Language:** Java
**Total Files:** 30
**Total Lines of Code:** 2500

**Technology Stack:**
- Spring Boot
- Maven

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| Java | 25 | 2000 | 200 | 150 |
| YAML | 5 | 500 | 30 | 10 |

---
*Generated by static analysis (ENABLE_AI=false)*

# module_deep_dive

Deep dive into modules

**Module/Directory Breakdown:**

| Module | Files | Subdirectories |
|--------|------:|---------------:|
| `src/main/java/` | 20 | 3 |
| `src/test/java/` | 10 | 2 |

---
*Generated by static analysis (ENABLE_AI=false)*

# APIs

APIs analysis

**Route Endpoints (from code):**

| Method | Path | File |
|--------|------|------|
| GET | `/api/shipments/{id}` | ShipController.java |
| POST | `/api/shipments` | ShipController.java |

---
*Generated by static analysis (ENABLE_AI=false)*

# events

events analysis

**Event/Messaging Systems Detected:**

- **Kafka**
  - Code: `OrderEventConsumer.java`

**Topics/Queues:**

| Name | Type | File |
|------|------|------|
| `order.created` | Kafka topic (consumer) | `OrderEventConsumer.java` |

---
*Generated by static analysis (ENABLE_AI=false)*

# DBs

databases analysis

**Connection Strings Detected:**

| Database Type | Config File |
|--------------|-------------|
| PostgreSQL | `application.yml` |

---
*Generated by static analysis (ENABLE_AI=false)*

# service_dependencies

Analyze service dependencies

*No module or provider dependencies found.*

---
*Generated by static analysis (ENABLE_AI=false)*
"""

SAMPLE_ARCH_IAC_WITH_DEPS = """\
# hl_overview

High level overview of the codebase

**Repository Name:** infra-network

**Primary Language:** Terraform
**Total Files:** 18
**Total Lines of Code:** 627

**Technology Stack:**
- Terraform

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| Terraform | 11 | 626 | 163 | 106 |
| Shell | 1 | 1 | 0 | 1 |

---
*Generated by static analysis (ENABLE_AI=false)*

# module_deep_dive

Deep dive into modules

**Module/Directory Breakdown:**

| Module | Files | Subdirectories |
|--------|------:|---------------:|
| `bastion/` | 3 | 0 |
| `emr/` | 5 | 0 |
| `vpc/` | 4 | 0 |

---
*Generated by static analysis (ENABLE_AI=false)*

# APIs

APIs analysis

*No API definitions, route annotations, or API Gateway resources detected.*

---
*Generated by static analysis (ENABLE_AI=false)*

# events

events analysis

*No event/messaging systems, brokers, or pub/sub patterns detected.*

---
*Generated by static analysis (ENABLE_AI=false)*

# DBs

databases analysis

*No database resources, connection strings, or data store configurations detected.*

---
*Generated by static analysis (ENABLE_AI=false)*

# service_dependencies

Analyze service dependencies

**Module Dependencies:**

| Module | Source | Type | File |
|--------|--------|------|------|
| `aws_vpc` | ./vpc | local | main.tf |
| `bastion_instance` | ./bastion | local | main.tf |
| `emr` | ./emr | local | main.tf |

**Module Dependency Chain:**
```
  root -> aws_vpc (source: ./vpc)
  root -> bastion_instance (source: ./bastion)
  root -> emr (source: ./emr)
```

**Providers:**

| Provider | File |
|----------|------|
| `aws` | main.tf |

**Outputs Exposed:** 6
- `vpc_1_id` (vpc/outputs.tf)
- `sn_1a_id` (vpc/outputs.tf)
- `instance_id` (bastion/outputs.tf)
- `emr_cluster_master_public_dns` (emr/outputs.tf)
- `emr_endpoint_dns_entry` (bastion/outputs.tf)
- `service_name` (emr/outputs.tf)

---
*Generated by static analysis (ENABLE_AI=false)*
"""

SAMPLE_ARCH_OAS_SERVICE = """\
# hl_overview

High level overview of the codebase

**Repository Name:** user-api

**Primary Language:** Python
**Total Files:** 20
**Total Lines of Code:** 1500

**Technology Stack:**
- FastAPI

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| Python | 18 | 1400 | 100 | 50 |

---
*Generated by static analysis (ENABLE_AI=false)*

# APIs

APIs analysis

**OpenAPI Spec: User Management API**
- File: `openapi.yaml`
- Version: 3.0.0
- Endpoints: 3

| Method | Path | Summary |
|--------|------|---------|
| GET | `/users` | List all users |
| POST | `/users` | Create a new user |
| DELETE | `/users/{id}` | Delete a user |

---
*Generated by static analysis (ENABLE_AI=false)*

# events

events analysis

*No event/messaging systems, brokers, or pub/sub patterns detected.*

---
*Generated by static analysis (ENABLE_AI=false)*

# DBs

databases analysis

**Database Services (Docker Compose):**

| Database | File |
|----------|------|
| MongoDB | `docker-compose.yml` |

---
*Generated by static analysis (ENABLE_AI=false)*

# service_dependencies

Analyze service dependencies

*No module or provider dependencies found.*

---
*Generated by static analysis (ENABLE_AI=false)*
"""

# --- Fixture with resources section for infrastructure diagram testing ---

SAMPLE_ARCH_IAC_WITH_RESOURCES = """\
# hl_overview

High level overview of the codebase

**Repository Name:** infra-network

**Primary Language:** Terraform
**Total Files:** 18
**Total Lines of Code:** 627

**Technology Stack:**
- Terraform

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| Terraform | 11 | 626 | 163 | 106 |

---
*Generated by static analysis (ENABLE_AI=false)*

# module_deep_dive

Deep dive into modules

**Module/Directory Breakdown:**

| Module | Files | Subdirectories |
|--------|------:|---------------:|
| `bastion/` | 3 | 0 |
| `emr/` | 5 | 0 |
| `vpc/` | 4 | 0 |

---
*Generated by static analysis (ENABLE_AI=false)*

# APIs

APIs analysis

*No API definitions, route annotations, or API Gateway resources detected.*

---
*Generated by static analysis (ENABLE_AI=false)*

# events

events analysis

*No event/messaging systems, brokers, or pub/sub patterns detected.*

---
*Generated by static analysis (ENABLE_AI=false)*

# DBs

databases analysis

*No database resources, connection strings, or data store configurations detected.*

---
*Generated by static analysis (ENABLE_AI=false)*

# service_dependencies

Analyze service dependencies

**Module Dependencies:**

| Module | Source | Type | File |
|--------|--------|------|------|
| `aws_vpc` | ./vpc | local | main.tf |
| `bastion_instance` | ./bastion | local | main.tf |
| `emr` | ./emr | local | main.tf |

**Module Dependency Chain:**
```
  root -> aws_vpc (source: ./vpc)
  root -> bastion_instance (source: ./bastion)
  root -> emr (source: ./emr)
```

**Providers:**

| Provider | File |
|----------|------|
| `aws` | main.tf |

**Outputs Exposed:** 6
- `vpc_1_id` (vpc/outputs.tf)
- `sn_1a_id` (vpc/outputs.tf)
- `instance_id` (bastion/outputs.tf)
- `emr_cluster_master_public_dns` (emr/outputs.tf)
- `emr_endpoint_dns_entry` (bastion/outputs.tf)
- `service_name` (emr/outputs.tf)

---
*Generated by static analysis (ENABLE_AI=false)*

# core_entities

Core entities and their relationships

**Terraform Resource Groups:**

| Group | Resources | Files |
|-------|----------:|-------|
| Vpc | 7 | vpc/vpc.tf, bastion/bastion.tf, emr/emr.tf |
| Lb | 7 | emr/emr.tf |
| Route | 6 | vpc/vpc.tf |
| Iam | 5 | bastion/bastion.tf, emr/emr.tf |
| Subnet | 4 | vpc/vpc.tf |
| Security | 3 | vpc/vpc.tf |
| Instance | 2 | bastion/bastion.tf, emr/emr.tf |
| Emr | 1 | emr/emr.tf |
| Internet | 1 | vpc/vpc.tf |

---
*Generated by static analysis (ENABLE_AI=false)*

# authentication

Authentication mechanisms analysis

**Authentication/IAM Resources (Terraform):**

| Resource Type | Name | File |
|--------------|------|------|
| `aws_iam_instance_profile` | emr_iam_instance_profile | emr/emr.tf |
| `aws_iam_instance_profile` | bastion_iam_instance_profile | bastion/bastion.tf |
| `aws_iam_role` | emr_iam_role | emr/emr.tf |
| `aws_iam_role` | bastion_iam_role | bastion/bastion.tf |
| `aws_iam_role_policy` | iam_emr_service_policy | emr/emr.tf |

---
*Generated by static analysis (ENABLE_AI=false)*

# authorization

Authorization and access control analysis

**Authorization/Access Control Resources (Terraform):**

| Resource Type | Name | Category | File |
|--------------|------|----------|------|
| `aws_iam_role_policy` | iam_emr_service_policy | IAM | emr/emr.tf |
| `aws_security_group` | sg_1 | Security | vpc/vpc.tf |
| `aws_security_group` | sg_2 | Security | vpc/vpc.tf |
| `aws_security_group` | sg_3 | Security | vpc/vpc.tf |

---
*Generated by static analysis (ENABLE_AI=false)*

# resources

Detailed analysis of infrastructure resources

**Infrastructure Resources:**

| Resource Type | Name | Category | File |
|--------------|------|----------|------|
| `aws_instance` | emr_test_instance | Compute/EC2 | emr/emr.tf |
| `aws_instance` | bastion_instance | Compute/EC2 | bastion/bastion.tf |
| `aws_emr_cluster` | emr_cluster | Compute/EMR | emr/emr.tf |
| `aws_iam_instance_profile` | emr_iam_instance_profile | IAM | emr/emr.tf |
| `aws_iam_role` | emr_iam_role | IAM | emr/emr.tf |
| `aws_iam_role_policy` | iam_emr_service_policy | IAM | emr/emr.tf |
| `aws_lb` | emr_lb | Load Balancing | emr/emr.tf |
| `aws_lb_listener` | emr_test_lb_listener | Load Balancing | emr/emr.tf |
| `aws_vpc` | vpc_1 | Networking | vpc/vpc.tf |
| `aws_subnet` | sn_1a | Networking | vpc/vpc.tf |
| `aws_internet_gateway` | ig_1 | Networking | vpc/vpc.tf |
| `aws_security_group` | sg_1 | Security | vpc/vpc.tf |

**Total Resources:** 12

**Resources by Category:**

| Category | Count |
|----------|------:|
| Compute/EC2 | 2 |
| Compute/EMR | 1 |
| IAM | 3 |
| Load Balancing | 2 |
| Networking | 3 |
| Security | 1 |

---
*Generated by static analysis (ENABLE_AI=false)*
"""


class TestMermaidDiagramGeneratorParsing(unittest.TestCase):
    """Tests for the .arch.md parsing logic."""

    def test_parse_single_repo(self):
        """Single repo content is parsed correctly."""
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        self.assertEqual(len(gen._parsed_repos), 1)
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["display_name"], "aws-terraform-emr-network")
        self.assertEqual(repo["primary_language"], "Terraform")
        self.assertEqual(repo["total_loc"], 627)
        self.assertEqual(repo["total_files"], 18)

    def test_parse_tech_stack(self):
        """Tech stack list is extracted."""
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["tech_stack"], ["Terraform", "Docker"])

    def test_parse_language_breakdown(self):
        """Language breakdown table is parsed into lang->LOC dict."""
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["languages"]["Terraform"], 626)
        self.assertEqual(repo["languages"]["Shell"], 1)

    def test_parse_modules(self):
        """Module breakdown table is parsed."""
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        repo = gen._parsed_repos[0]
        self.assertEqual(len(repo["modules"]), 4)
        mod_names = {m["name"] for m in repo["modules"]}
        self.assertEqual(mod_names, {"arch-docs", "bastion", "emr", "vpc"})
        emr = next(m for m in repo["modules"] if m["name"] == "emr")
        self.assertEqual(emr["files"], 5)

    def test_parse_multiple_repos(self):
        """Multiple repos are all parsed."""
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        self.assertEqual(len(gen._parsed_repos), 2)

    def test_empty_content_skipped(self):
        """Empty content is skipped."""
        gen = MermaidDiagramGenerator({"repo1": "", "repo2": SAMPLE_ARCH_CONTENT_1})
        self.assertEqual(len(gen._parsed_repos), 1)

    def test_empty_dict(self):
        """Empty dict produces no parsed repos."""
        gen = MermaidDiagramGenerator({})
        self.assertEqual(gen._parsed_repos, [])


class TestMermaidDiagramGeneratorOverview(unittest.TestCase):
    """Tests for the overview diagram generation."""

    def test_overview_contains_mermaid_block(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_overview_diagram()
        self.assertIn("```mermaid", result)
        self.assertIn("graph TD", result)
        self.assertIn("```", result)

    def test_overview_contains_repo_info(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_overview_diagram()
        self.assertIn("aws-terraform-emr-network", result)
        self.assertIn("Terraform", result)
        self.assertIn("627", result)

    def test_overview_multiple_repos(self):
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        result = gen._generate_overview_diagram()
        self.assertIn("aws-terraform-emr-network", result)
        self.assertIn("backend-api", result)

    def test_overview_has_classdef_styling(self):
        """Overview diagram includes classDef styling."""
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_overview_diagram()
        self.assertIn("classDef", result)
        self.assertIn("iacNode", result)

    def test_overview_uses_typed_subgraph(self):
        """Overview uses typed subgraph label instead of generic."""
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_overview_diagram()
        # Single IaC repo should get "Infrastructure as Code" label
        self.assertIn("Infrastructure as Code", result)

    def test_overview_multiple_groups(self):
        """Repos of different types get separate subgraphs."""
        gen = MermaidDiagramGenerator({
            "iac": SAMPLE_ARCH_IAC_WITH_DEPS,
            "svc": SAMPLE_ARCH_API_SERVICE,
        })
        result = gen._generate_overview_diagram()
        self.assertIn("Infrastructure as Code", result)
        self.assertIn("Application Services", result)

    def test_overview_has_connections_for_shared_events(self):
        """Repos sharing event topics get edges in overview."""
        gen = MermaidDiagramGenerator({
            "order": SAMPLE_ARCH_API_SERVICE,
            "ship": SAMPLE_ARCH_SHIPPING_SERVICE,
        })
        result = gen._generate_overview_diagram()
        self.assertIn("event: order.created", result)

    def test_overview_has_connections_for_shared_db(self):
        """Repos sharing DB type get dotted edges."""
        gen = MermaidDiagramGenerator({
            "order": SAMPLE_ARCH_API_SERVICE,
            "ship": SAMPLE_ARCH_SHIPPING_SERVICE,
        })
        result = gen._generate_overview_diagram()
        self.assertIn("shared PostgreSQL", result)


class TestMermaidDiagramGeneratorTechStack(unittest.TestCase):
    """Tests for the tech stack diagram generation."""

    def test_tech_stack_contains_mermaid_block(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_tech_stack_diagram()
        self.assertIn("```mermaid", result)
        self.assertIn("graph LR", result)

    def test_tech_stack_groups_repos(self):
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        result = gen._generate_tech_stack_diagram()
        # Both repos have Docker and Terraform
        self.assertIn("Docker", result)
        self.assertIn("Terraform", result)
        # repo2 also has Maven and Spring Boot
        self.assertIn("Maven", result)
        self.assertIn("Spring Boot", result)

    def test_tech_stack_empty_when_no_tech(self):
        """Returns empty string when no tech stack data."""
        content = "**Repository Name:** bare\n**Primary Language:** Unknown\n"
        gen = MermaidDiagramGenerator({"repo1": content})
        result = gen._generate_tech_stack_diagram()
        self.assertEqual(result, "")

    def test_tech_stack_has_styling(self):
        """Tech stack diagram includes classDef styling."""
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_tech_stack_diagram()
        self.assertIn("classDef", result)


class TestMermaidDiagramGeneratorModules(unittest.TestCase):
    """Tests for the module structure diagram generation."""

    def test_module_diagrams_per_repo(self):
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        result = gen._generate_module_diagrams()
        # Should have two H3 headers
        self.assertIn("### aws-terraform-emr-network", result)
        self.assertIn("### backend-api", result)
        # Should have mermaid blocks
        self.assertEqual(result.count("```mermaid"), 2)

    def test_module_diagram_contains_modules(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_module_diagrams()
        self.assertIn("emr", result)
        self.assertIn("vpc", result)
        self.assertIn("bastion", result)
        self.assertIn("5 files", result)

    def test_module_diagram_empty_when_no_modules(self):
        content = "**Repository Name:** bare\n**Primary Language:** Go\n"
        gen = MermaidDiagramGenerator({"repo1": content})
        result = gen._generate_module_diagrams()
        self.assertEqual(result, "")


class TestMermaidDiagramGeneratorPieChart(unittest.TestCase):
    """Tests for the language distribution pie chart."""

    def test_pie_chart_contains_mermaid_block(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_language_pie_chart()
        self.assertIn("```mermaid", result)
        self.assertIn("pie title", result)

    def test_pie_chart_aggregates_across_repos(self):
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        result = gen._generate_language_pie_chart()
        # Terraform: 626 (repo1) + 300 (repo2) = 926
        self.assertIn('"Terraform" : 926', result)
        # Java: 7200 (repo2 only)
        self.assertIn('"Java" : 7200', result)

    def test_pie_chart_empty_when_no_languages(self):
        content = "**Repository Name:** bare\n**Primary Language:** Unknown\n"
        gen = MermaidDiagramGenerator({"repo1": content})
        result = gen._generate_language_pie_chart()
        self.assertEqual(result, "")


class TestMermaidDiagramGeneratorFullOutput(unittest.TestCase):
    """Tests for the complete generate_all() output."""

    def test_generate_all_structure(self):
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        result = gen.generate_all(generated_date="2026-02-13")
        self.assertIn("# Cross-Repository Architecture Overview", result)
        self.assertIn("2026-02-13", result)
        self.assertIn("## Network/Architecture Diagram", result)
        self.assertIn("## Technology Stack", result)
        self.assertIn("## Module Structure", result)
        self.assertIn("## Language Distribution", result)
        self.assertIn("*Generated by static analysis (ENABLE_AI=false)*", result)

    def test_generate_all_has_mermaid_blocks(self):
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        result = gen.generate_all()
        # lifecycle + overview + tech_stack + 2 module diagrams + pie = 6 mermaid blocks
        self.assertEqual(result.count("```mermaid"), 6)

    def test_generate_all_empty(self):
        gen = MermaidDiagramGenerator({})
        result = gen.generate_all(generated_date="2026-02-13")
        self.assertIn("No repository analysis data available", result)
        self.assertIn("ENABLE_AI=false", result)

    def test_generate_all_single_repo(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen.generate_all()
        self.assertIn("## Network/Architecture Diagram", result)
        # 1 overview + 1 tech_stack + 1 module + 1 pie = 4 diagrams
        self.assertEqual(result.count("```mermaid"), 4)

    def test_custom_date_in_output(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen.generate_all(generated_date="2025-01-01")
        self.assertIn("2025-01-01", result)

    def test_generate_all_includes_infra_diagram(self):
        """Repos with terraform_resources get infrastructure diagram."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen.generate_all()
        self.assertIn("## Infrastructure Architecture", result)

    def test_generate_all_no_infra_for_non_terraform(self):
        """Non-terraform repos don't get infrastructure diagram."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        result = gen.generate_all()
        self.assertNotIn("## Infrastructure Architecture", result)


class TestMermaidDiagramGeneratorHelpers(unittest.TestCase):
    """Tests for helper methods."""

    def test_safe_id(self):
        gen = MermaidDiagramGenerator({})
        self.assertEqual(gen._safe_id("my-repo", 0), "repo0_my_repo")
        self.assertEqual(gen._safe_id("repo with spaces", 1), "repo1_repo_with_spaces")
        self.assertEqual(gen._safe_id("hello.world", 2), "repo2_hello_world")

    def test_safe_subgraph_id(self):
        gen = MermaidDiagramGenerator({})
        self.assertEqual(gen._safe_subgraph_id("Terraform"), "sg_Terraform")
        self.assertEqual(gen._safe_subgraph_id("Spring Boot"), "sg_Spring_Boot")
        self.assertEqual(gen._safe_subgraph_id("Go Modules"), "sg_Go_Modules")

    def test_classify_repo_iac(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_DEPS})
        repo = gen._parsed_repos[0]
        self.assertEqual(gen._classify_repo(repo), "iac")

    def test_classify_repo_service(self):
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        repo = gen._parsed_repos[0]
        self.assertEqual(gen._classify_repo(repo), "service")

    def test_node_shape_storage(self):
        gen = MermaidDiagramGenerator({})
        result = gen._node_shape("db1", "PostgreSQL", "storage")
        self.assertIn('("PostgreSQL")', result)

    def test_node_shape_compute(self):
        gen = MermaidDiagramGenerator({})
        result = gen._node_shape("emr1", "EMR Cluster", "compute")
        self.assertIn('{{"EMR Cluster"}}', result)

    def test_node_shape_default(self):
        gen = MermaidDiagramGenerator({})
        result = gen._node_shape("n1", "Some Node", "default")
        self.assertIn('["Some Node"]', result)

    def test_get_style_definitions(self):
        gen = MermaidDiagramGenerator({})
        styles = gen._get_style_definitions()
        self.assertGreater(len(styles), 0)
        self.assertTrue(all("classDef" in s for s in styles))
        class_names = [s.split()[1] for s in styles]
        self.assertIn("iacNode", class_names)
        self.assertIn("serviceNode", class_names)
        self.assertIn("dataNode", class_names)


class TestMermaidDiagramGeneratorWithRealData(unittest.TestCase):
    """Tests using the real sample arch.md from the outputs directory."""

    @classmethod
    def setUpClass(cls):
        arch_file = os.path.join(
            os.path.dirname(__file__), '..', '..', 'outputs',
            'aws-terraform-emr-network-arch.md'
        )
        if os.path.exists(arch_file):
            with open(arch_file, 'r') as f:
                cls.real_content = f.read()
            cls.has_real_data = True
        else:
            cls.has_real_data = False

    def test_parses_real_arch_file(self):
        """Parser handles real .arch.md output."""
        if not self.has_real_data:
            self.skipTest("No real arch file available")
        gen = MermaidDiagramGenerator({"emr": self.real_content})
        self.assertEqual(len(gen._parsed_repos), 1)
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["display_name"], "terraform")
        self.assertEqual(repo["primary_language"], "Terraform")
        self.assertEqual(repo["total_loc"], 627)

    def test_generates_diagrams_from_real_data(self):
        """Full diagram generation works with real data."""
        if not self.has_real_data:
            self.skipTest("No real arch file available")
        gen = MermaidDiagramGenerator({"emr": self.real_content})
        result = gen.generate_all()
        self.assertIn("```mermaid", result)
        self.assertIn("terraform", result.lower())

    def test_real_data_has_infrastructure_diagram(self):
        """Real data with resources section produces infrastructure diagram."""
        if not self.has_real_data:
            self.skipTest("No real arch file available")
        gen = MermaidDiagramGenerator({"emr": self.real_content})
        result = gen.generate_all()
        self.assertIn("## Infrastructure Architecture", result)

    def test_real_data_parses_resources(self):
        """Real data resources section is parsed."""
        if not self.has_real_data:
            self.skipTest("No real arch file available")
        gen = MermaidDiagramGenerator({"emr": self.real_content})
        repo = gen._parsed_repos[0]
        self.assertGreater(len(repo["terraform_resources"]), 0)
        self.assertGreater(len(repo["resource_categories"]), 0)


class TestParsingResources(unittest.TestCase):
    """Tests for parsing the # resources section."""

    def test_parse_terraform_resources(self):
        """Individual terraform resources are parsed from resources table."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        self.assertGreater(len(repo["terraform_resources"]), 0)
        types = {r["type"] for r in repo["terraform_resources"]}
        self.assertIn("aws_instance", types)
        self.assertIn("aws_emr_cluster", types)
        self.assertIn("aws_vpc", types)
        self.assertIn("aws_lb", types)

    def test_parse_resource_categories(self):
        """Resource category summary is parsed."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        self.assertIn("Compute/EC2", repo["resource_categories"])
        self.assertEqual(repo["resource_categories"]["Compute/EC2"], 2)
        self.assertIn("Compute/EMR", repo["resource_categories"])
        self.assertEqual(repo["resource_categories"]["Compute/EMR"], 1)
        self.assertIn("Networking", repo["resource_categories"])
        self.assertEqual(repo["resource_categories"]["Networking"], 3)

    def test_parse_resource_details(self):
        """Resource entries have all required fields."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        emr = next(r for r in repo["terraform_resources"] if r["type"] == "aws_emr_cluster")
        self.assertEqual(emr["name"], "emr_cluster")
        self.assertEqual(emr["category"], "Compute/EMR")
        self.assertEqual(emr["file"], "emr/emr.tf")

    def test_no_resources_section(self):
        """Repos without resources section have empty terraform_resources."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["terraform_resources"], [])
        self.assertEqual(repo["resource_categories"], {})


class TestParsingAuthentication(unittest.TestCase):
    """Tests for parsing the # authentication section."""

    def test_parse_iam_resources(self):
        """IAM resources from authentication section are parsed."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        self.assertGreater(len(repo["iam_resources"]), 0)
        types = {r["type"] for r in repo["iam_resources"]}
        self.assertIn("aws_iam_role", types)
        self.assertIn("aws_iam_instance_profile", types)

    def test_parse_iam_details(self):
        """IAM resource entries have name and file."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        role = next(r for r in repo["iam_resources"] if r["name"] == "emr_iam_role")
        self.assertEqual(role["type"], "aws_iam_role")
        self.assertEqual(role["file"], "emr/emr.tf")


class TestParsingAuthorization(unittest.TestCase):
    """Tests for parsing the # authorization section."""

    def test_parse_security_resources(self):
        """Security resources from authorization section are parsed."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        self.assertGreater(len(repo["security_resources"]), 0)
        types = {r["type"] for r in repo["security_resources"]}
        self.assertIn("aws_security_group", types)
        self.assertIn("aws_iam_role_policy", types)

    def test_parse_security_categories(self):
        """Security resources have category field."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        sg = next(r for r in repo["security_resources"] if r["type"] == "aws_security_group")
        self.assertEqual(sg["category"], "Security")


class TestParsingCoreEntities(unittest.TestCase):
    """Tests for parsing the # core_entities section."""

    def test_parse_resource_groups(self):
        """Resource groups from core_entities are parsed."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        self.assertGreater(len(repo["resource_groups"]), 0)
        group_names = {g["group"] for g in repo["resource_groups"]}
        self.assertIn("Vpc", group_names)
        self.assertIn("Iam", group_names)
        self.assertIn("Emr", group_names)

    def test_parse_resource_group_counts(self):
        """Resource groups have correct counts."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        vpc = next(g for g in repo["resource_groups"] if g["group"] == "Vpc")
        self.assertEqual(vpc["resources"], 7)


class TestParsingProviders(unittest.TestCase):
    """Tests for parsing providers from service_dependencies."""

    def test_parse_providers(self):
        """Providers are parsed from service_dependencies section."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        repo = gen._parsed_repos[0]
        self.assertIn("aws", repo["providers"])

    def test_no_providers_for_non_iac(self):
        """Non-IaC repos have empty providers."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["providers"], [])


class TestInfrastructureDiagram(unittest.TestCase):
    """Tests for the new infrastructure architecture diagram."""

    def test_infra_diagram_generated(self):
        """Infrastructure diagram is generated for repos with terraform_resources."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_infrastructure_diagram()
        self.assertIn("```mermaid", result)
        self.assertIn("graph TD", result)

    def test_infra_diagram_has_layers(self):
        """Diagram has subgraphs for architectural layers."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_infrastructure_diagram()
        self.assertIn("Compute", result)
        self.assertIn("Network", result)
        self.assertIn("Security", result)

    def test_infra_diagram_has_edges(self):
        """Diagram has edges between layers."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_infrastructure_diagram()
        self.assertIn("runs within", result)

    def test_infra_diagram_has_styling(self):
        """Diagram includes classDef styling."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_infrastructure_diagram()
        self.assertIn("classDef", result)
        self.assertIn("computeNode", result)
        self.assertIn("networkNode", result)
        self.assertIn("securityNode", result)

    def test_infra_diagram_has_provisions_edge(self):
        """Repo node connects to resources via 'provisions' edge."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_infrastructure_diagram()
        self.assertIn("provisions", result)

    def test_infra_diagram_empty_for_non_terraform(self):
        """No infrastructure diagram for non-terraform repos."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        result = gen._generate_infrastructure_diagram()
        self.assertEqual(result, "")

    def test_infra_diagram_resource_names_readable(self):
        """Resource type names are readable (aws_ prefix stripped)."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_infrastructure_diagram()
        # Should show "Instance" or "Emr Cluster" not "aws_instance" or "aws_emr_cluster"
        self.assertNotIn("aws_instance", result)
        self.assertNotIn("aws_emr_cluster", result)


class TestInferRepoConnections(unittest.TestCase):
    """Tests for the _infer_repo_connections helper."""

    def test_shared_event_topics_produce_connections(self):
        """Repos sharing Kafka topics get solid connections."""
        gen = MermaidDiagramGenerator({
            "order": SAMPLE_ARCH_API_SERVICE,
            "ship": SAMPLE_ARCH_SHIPPING_SERVICE,
        })
        connections = gen._infer_repo_connections()
        labels = [c[2] for c in connections]
        self.assertTrue(any("order.created" in l for l in labels))

    def test_shared_db_produces_connections(self):
        """Repos sharing DB type get dotted connections."""
        gen = MermaidDiagramGenerator({
            "order": SAMPLE_ARCH_API_SERVICE,
            "ship": SAMPLE_ARCH_SHIPPING_SERVICE,
        })
        connections = gen._infer_repo_connections()
        dotted = [c for c in connections if c[3] == "dotted"]
        labels = [c[2] for c in dotted]
        self.assertTrue(any("PostgreSQL" in l for l in labels))

    def test_no_connections_for_unrelated_repos(self):
        """Repos with nothing in common produce no connections."""
        gen = MermaidDiagramGenerator({
            "iac": SAMPLE_ARCH_IAC_WITH_DEPS,
            "api": SAMPLE_ARCH_OAS_SERVICE,
        })
        connections = gen._infer_repo_connections()
        self.assertEqual(len(connections), 0)


class TestSequenceDiagramParsing(unittest.TestCase):
    """Tests for parsing APIs, events, DBs, service_deps from .arch.md."""

    def test_parse_route_endpoints(self):
        """Route endpoint table is parsed into api_endpoints list."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        repo = gen._parsed_repos[0]
        self.assertEqual(len(repo["api_endpoints"]), 3)
        methods = {ep["method"] for ep in repo["api_endpoints"]}
        self.assertEqual(methods, {"GET", "POST", "PUT"})
        paths = {ep["path"] for ep in repo["api_endpoints"]}
        self.assertIn("/api/orders", paths)
        self.assertIn("/api/orders/{id}", paths)

    def test_parse_oas_endpoints(self):
        """OpenAPI spec table (Method | Path | Summary) is parsed."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_OAS_SERVICE})
        repo = gen._parsed_repos[0]
        self.assertEqual(len(repo["api_endpoints"]), 3)
        methods = {ep["method"] for ep in repo["api_endpoints"]}
        self.assertEqual(methods, {"GET", "POST", "DELETE"})
        # Check summary is captured in detail
        post_ep = next(ep for ep in repo["api_endpoints"] if ep["method"] == "POST")
        self.assertIn("Create", post_ep["detail"])

    def test_parse_event_brokers(self):
        """Broker names extracted from events section bullet list."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["event_brokers"], ["Kafka"])

    def test_parse_event_topics(self):
        """Topics/Queues table parsed from events section."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        repo = gen._parsed_repos[0]
        self.assertEqual(len(repo["event_topics"]), 2)
        topic_names = {t["name"] for t in repo["event_topics"]}
        self.assertEqual(topic_names, {"order.created", "order.shipped"})

    def test_parse_databases(self):
        """Database types extracted from DBs section tables."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["databases"], ["PostgreSQL"])

    def test_parse_databases_docker(self):
        """Docker Compose database types extracted."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_OAS_SERVICE})
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["databases"], ["MongoDB"])

    def test_parse_module_chain(self):
        """Module dependency chain extracted from service_dependencies."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_IAC_WITH_DEPS})
        repo = gen._parsed_repos[0]
        self.assertEqual(len(repo["module_chain"]), 3)
        names = {m["name"] for m in repo["module_chain"]}
        self.assertEqual(names, {"aws_vpc", "bastion_instance", "emr"})
        vpc = next(m for m in repo["module_chain"] if m["name"] == "aws_vpc")
        self.assertEqual(vpc["source"], "./vpc")

    def test_parse_outputs(self):
        """Output bullet list parsed from service_dependencies."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_IAC_WITH_DEPS})
        repo = gen._parsed_repos[0]
        self.assertEqual(len(repo["outputs"]), 6)
        output_names = {o["name"] for o in repo["outputs"]}
        self.assertIn("vpc_1_id", output_names)
        self.assertIn("emr_cluster_master_public_dns", output_names)

    def test_parse_no_data_returns_empty(self):
        """Sections with 'No X detected' produce empty lists."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_IAC_WITH_DEPS})
        repo = gen._parsed_repos[0]
        self.assertEqual(repo["api_endpoints"], [])
        self.assertEqual(repo["event_brokers"], [])
        self.assertEqual(repo["event_topics"], [])
        self.assertEqual(repo["databases"], [])


class TestSequenceDiagramGeneration(unittest.TestCase):
    """Tests for sequence diagram output."""

    def test_api_flow_single_service(self):
        """Single API service generates Client -> Service -> DB flow."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        result = gen._generate_sequence_diagrams()
        self.assertIn("sequenceDiagram", result)
        self.assertIn("Client", result)
        self.assertIn("order-service", result)
        self.assertIn("POST /api/orders", result)
        self.assertIn("PostgreSQL", result)

    def test_api_flow_has_autonumber(self):
        """API flow includes autonumber."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        result = gen._generate_sequence_diagrams()
        self.assertIn("autonumber", result)

    def test_api_flow_has_activate_deactivate(self):
        """API flow uses activate/deactivate for lifeline visualization."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        result = gen._generate_sequence_diagrams()
        self.assertIn("activate", result)
        self.assertIn("deactivate", result)

    def test_api_flow_has_notes(self):
        """API flow includes Note annotations."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        result = gen._generate_sequence_diagrams()
        self.assertIn("Note over", result)
        self.assertIn("Validate request", result)

    def test_event_flow_cross_repo(self):
        """Two repos sharing a Kafka topic generate cross-repo event flow."""
        gen = MermaidDiagramGenerator({
            "order": SAMPLE_ARCH_API_SERVICE,
            "ship": SAMPLE_ARCH_SHIPPING_SERVICE,
        })
        result = gen._generate_sequence_diagrams()
        self.assertIn("Event-Driven Message Flow", result)
        self.assertIn("Kafka", result)
        self.assertIn("order.created", result)
        # Both services should appear
        self.assertIn("order-service", result)
        self.assertIn("shipping-service", result)

    def test_event_flow_has_async_note(self):
        """Event flow includes async message delivery note."""
        gen = MermaidDiagramGenerator({
            "order": SAMPLE_ARCH_API_SERVICE,
            "ship": SAMPLE_ARCH_SHIPPING_SERVICE,
        })
        result = gen._generate_sequence_diagrams()
        self.assertIn("Async message delivery", result)

    def test_event_flow_has_activate_deactivate(self):
        """Event flow uses activate/deactivate for consumer processing."""
        gen = MermaidDiagramGenerator({
            "order": SAMPLE_ARCH_API_SERVICE,
            "ship": SAMPLE_ARCH_SHIPPING_SERVICE,
        })
        result = gen._generate_sequence_diagrams()
        # Event flow should have activate for consumers
        event_section = result[result.index("Event-Driven"):]
        self.assertIn("activate", event_section)
        self.assertIn("deactivate", event_section)

    def test_combined_api_and_event(self):
        """API + event data generates both types of flows."""
        gen = MermaidDiagramGenerator({
            "order": SAMPLE_ARCH_API_SERVICE,
            "ship": SAMPLE_ARCH_SHIPPING_SERVICE,
        })
        result = gen._generate_sequence_diagrams()
        self.assertIn("API Request Flow", result)
        self.assertIn("Event-Driven Message Flow", result)
        # At least 2 sequenceDiagram blocks
        self.assertGreaterEqual(result.count("sequenceDiagram"), 2)

    def test_shared_db_cross_repo(self):
        """Two repos with same DB type can generate shared DB access flow."""
        gen = MermaidDiagramGenerator({
            "user": SAMPLE_ARCH_OAS_SERVICE,
        })
        result = gen._build_shared_db_flow()
        self.assertIsNone(result)

    def test_iac_fallback_provisioning(self):
        """IaC-only repos generate Terraform provisioning sequence."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_DEPS})
        result = gen._generate_sequence_diagrams()
        self.assertIn("Infrastructure Provisioning Sequence", result)
        self.assertIn("sequenceDiagram", result)
        # New enriched format uses Provision/Note style
        self.assertIn("Provision", result)
        self.assertIn("aws_vpc", result)
        self.assertIn("bastion_instance", result)
        self.assertIn("emr", result)

    def test_iac_flow_has_state_management(self):
        """IaC flow includes state file lock/unlock."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_DEPS})
        result = gen._generate_sequence_diagrams()
        self.assertIn("Lock state file", result)
        self.assertIn("Update state file", result)
        self.assertIn("Release lock", result)

    def test_iac_flow_has_terraform_plan(self):
        """IaC flow starts with terraform plan/apply."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_DEPS})
        result = gen._generate_sequence_diagrams()
        self.assertIn("terraform plan/apply", result)
        self.assertIn("Apply complete", result)

    def test_iac_flow_has_resource_diff(self):
        """IaC flow includes resource diff calculation."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_DEPS})
        result = gen._generate_sequence_diagrams()
        self.assertIn("Calculate resource diff", result)

    def test_iac_outputs_shown(self):
        """IaC provisioning shows output exposure arrows."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_DEPS})
        result = gen._generate_sequence_diagrams()
        self.assertIn("vpc_1_id", result)

    def test_iac_flow_with_resources_has_cloud_apis(self):
        """IaC flow with resource categories shows cloud API participants."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_sequence_diagrams()
        # Should have AWS API participants for resource categories present
        self.assertIn("AWS", result)
        self.assertIn("activate", result)
        self.assertIn("deactivate", result)

    def test_iac_flow_with_emr_has_polling_loop(self):
        """IaC flow with EMR resources includes polling loop."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_sequence_diagrams()
        self.assertIn("loop Poll until cluster ready", result)
        self.assertIn("Describe Cluster Status", result)

    def test_no_data_returns_empty(self):
        """Repos with no APIs/events/DBs/modules return empty string."""
        bare_content = "**Repository Name:** bare\n**Primary Language:** Go\n"
        gen = MermaidDiagramGenerator({"bare": bare_content})
        result = gen._generate_sequence_diagrams()
        self.assertEqual(result, "")

    def test_valid_mermaid_syntax(self):
        """Output contains valid sequenceDiagram syntax."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        result = gen._generate_sequence_diagrams()
        self.assertIn("```mermaid", result)
        self.assertIn("sequenceDiagram", result)
        self.assertIn("participant", result)
        self.assertIn("->>", result)

    def test_participant_names_safe(self):
        """Participant IDs contain no special chars."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        pid, display = gen._safe_participant("my-weird.service_name", 0)
        self.assertRegex(pid, r'^p\d+_[a-zA-Z0-9_]+$')
        self.assertEqual(display, "my-weird.service_name")


class TestSequenceInGenerateAll(unittest.TestCase):
    """Tests for sequence diagram integration in generate_all()."""

    def test_generate_all_includes_sequences(self):
        """generate_all() includes '## Service Interaction Sequences' when data exists."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        result = gen.generate_all()
        self.assertIn("## Service Interaction Sequences", result)

    def test_generate_all_diagram_count_increases(self):
        """Mermaid block count increases with sequence diagrams."""
        gen = MermaidDiagramGenerator({"svc": SAMPLE_ARCH_API_SERVICE})
        result = gen.generate_all()
        # overview + tech_stack + 1 module + pie + at least 1 sequence = 5+
        self.assertGreaterEqual(result.count("```mermaid"), 5)

    def test_generate_all_iac_repos_get_sequence(self):
        """IaC repos with module chain get provisioning sequence."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_DEPS})
        result = gen.generate_all()
        self.assertIn("## Service Interaction Sequences", result)
        self.assertIn("Infrastructure Provisioning", result)

    def test_generate_all_no_sequence_bare_repo(self):
        """Bare repo with only hl_overview has no sequence section."""
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        result = gen.generate_all()
        # These repos have no APIs/events/DBs/module_chain
        self.assertNotIn("## Service Interaction Sequences", result)


# --- Fixture: CloudFormation integration repo ---
SAMPLE_ARCH_CF_INTEGRATION = """\
# hl_overview

High level overview of the codebase

**Repository Name:** terraform-cf-integration

**Primary Language:** Terraform
**Total Files:** 11
**Total Lines of Code:** 1646

**Technology Stack:**
- Terraform

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| JSON | 2 | 1577 | 0 | 0 |
| Terraform | 3 | 69 | 18 | 0 |

---
*Generated by static analysis (ENABLE_AI=false)*

# module_deep_dive

Deep dive into modules

**Module/Directory Breakdown:**

| Module | Files | Subdirectories |
|--------|------:|---------------:|
| `arch-docs/` | 2 | 0 |
| `cf-templates/` | 2 | 0 |

---
*Generated by static analysis (ENABLE_AI=false)*

# service_dependencies

Analyze service dependencies

**Module Dependencies:**

*No module dependencies detected.*

**Providers:**

| Provider | File |
|----------|------|
| `aws` | main.tf |

**Outputs Exposed:** 0

---
*Generated by static analysis (ENABLE_AI=false)*

# core_entities

Core entities and their relationships

**Terraform Resource Groups:**

| Group | Resources | Files |
|-------|----------:|-------|
| Cloudformation | 2 | main.tf |

---
*Generated by static analysis (ENABLE_AI=false)*

# resources

Detailed analysis of infrastructure resources

**Infrastructure Resources:**

| Resource Type | Name | Category | File |
|--------------|------|----------|------|
| `aws_cloudformation_stack` | iam | CloudFormation | main.tf |
| `aws_cloudformation_stack` | vpc | CloudFormation | main.tf |

**Total Resources:** 2

**Resources by Category:**

| Category | Count |
|----------|------:|
| CloudFormation | 2 |

---
*Generated by static analysis (ENABLE_AI=false)*
"""

# --- Fixture: IAC with VPC endpoints ---
SAMPLE_ARCH_IAC_WITH_VPC_ENDPOINTS = """\
# hl_overview

High level overview of the codebase

**Repository Name:** infra-network

**Primary Language:** Terraform
**Total Files:** 18
**Total Lines of Code:** 627

**Technology Stack:**
- Terraform

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| Terraform | 11 | 626 | 163 | 106 |

---
*Generated by static analysis (ENABLE_AI=false)*

# module_deep_dive

Deep dive into modules

**Module/Directory Breakdown:**

| Module | Files | Subdirectories |
|--------|------:|---------------:|
| `bastion/` | 3 | 0 |
| `emr/` | 5 | 0 |
| `vpc/` | 4 | 0 |

---
*Generated by static analysis (ENABLE_AI=false)*

# service_dependencies

Analyze service dependencies

**Module Dependencies:**

| Module | Source | Type | File |
|--------|--------|------|------|
| `aws_vpc` | ./vpc | local | main.tf |
| `bastion_instance` | ./bastion | local | main.tf |
| `emr` | ./emr | local | main.tf |

**Module Dependency Chain:**
```
  root -> aws_vpc (source: ./vpc)
  root -> bastion_instance (source: ./bastion)
  root -> emr (source: ./emr)
```

**Providers:**

| Provider | File |
|----------|------|
| `aws` | main.tf |

**Outputs Exposed:** 6
- `vpc_1_id` (vpc/outputs.tf)
- `sn_1a_id` (vpc/outputs.tf)
- `instance_id` (bastion/outputs.tf)
- `emr_cluster_master_public_dns` (emr/outputs.tf)
- `emr_endpoint_dns_entry` (bastion/outputs.tf)
- `service_name` (emr/outputs.tf)

---
*Generated by static analysis (ENABLE_AI=false)*

# resources

Detailed analysis of infrastructure resources

**Infrastructure Resources:**

| Resource Type | Name | Category | File |
|--------------|------|----------|------|
| `aws_instance` | emr_test_instance | Compute/EC2 | emr/emr.tf |
| `aws_emr_cluster` | emr_cluster | Compute/EMR | emr/emr.tf |
| `aws_iam_role` | emr_iam_role | IAM | emr/emr.tf |
| `aws_vpc` | vpc_1 | Networking | vpc/vpc.tf |
| `aws_subnet` | sn_1a | Networking | vpc/vpc.tf |
| `aws_internet_gateway` | ig_1 | Networking | vpc/vpc.tf |
| `aws_security_group` | sg_1 | Security | vpc/vpc.tf |
| `aws_vpc_endpoint` | s3 | Networking | vpc/vpc.tf |
| `aws_vpc_endpoint` | dynamodb | Networking | vpc/vpc.tf |
| `aws_vpc_endpoint` | kinesis_streams | Networking | vpc/vpc.tf |

**Total Resources:** 10

**Resources by Category:**

| Category | Count |
|----------|------:|
| Compute/EC2 | 1 |
| Compute/EMR | 1 |
| IAM | 1 |
| Networking | 6 |
| Security | 1 |

---
*Generated by static analysis (ENABLE_AI=false)*

# authentication

Authentication mechanisms analysis

**Authentication/IAM Resources (Terraform):**

| Resource Type | Name | File |
|--------------|------|------|
| `aws_iam_role` | emr_iam_role | emr/emr.tf |

---
*Generated by static analysis (ENABLE_AI=false)*

# authorization

Authorization and access control analysis

**Authorization/Access Control Resources (Terraform):**

| Resource Type | Name | Category | File |
|--------------|------|----------|------|
| `aws_security_group` | sg_1 | Security | vpc/vpc.tf |

---
*Generated by static analysis (ENABLE_AI=false)*
"""


class TestOverviewAWSServiceNodes(unittest.TestCase):
    """Tests for AWS service nodes in the overview diagram."""

    def test_overview_has_aws_services_subgraph(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_overview_diagram()
        self.assertIn("AWS Cloud Services", result)

    def test_overview_has_vpc_service_node(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_overview_diagram()
        self.assertIn("svc_VPC", result)
        self.assertIn("AWS VPC", result)

    def test_overview_has_emr_service_node(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_overview_diagram()
        self.assertIn("svc_EMR", result)
        self.assertIn("AWS EMR", result)

    def test_overview_has_iam_service_node(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_overview_diagram()
        self.assertIn("svc_IAM", result)

    def test_overview_repo_to_service_edges(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_overview_diagram()
        self.assertIn("provisions network", result)
        self.assertIn("deploys cluster", result)

    def test_overview_service_structural_edges(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_overview_diagram()
        self.assertIn("runs within", result)
        self.assertIn("uses roles", result)

    def test_overview_service_node_styling(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_overview_diagram()
        self.assertIn("class svc_VPC securityNode", result)
        self.assertIn("class svc_EMR computeNode", result)

    def test_overview_no_services_for_bare_repo(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_overview_diagram()
        self.assertNotIn("AWS Cloud Services", result)

    def test_overview_s3_from_vpc_endpoint(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_VPC_ENDPOINTS})
        result = gen._generate_overview_diagram()
        self.assertIn("svc_S3", result)
        self.assertIn("S3", result)

    def test_overview_dynamodb_from_vpc_endpoint(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_VPC_ENDPOINTS})
        result = gen._generate_overview_diagram()
        self.assertIn("svc_DynamoDB", result)

    def test_overview_kinesis_from_vpc_endpoint(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_VPC_ENDPOINTS})
        result = gen._generate_overview_diagram()
        self.assertIn("svc_Kinesis", result)

    def test_overview_cf_service_node(self):
        gen = MermaidDiagramGenerator({"cf": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_overview_diagram()
        self.assertIn("svc_CF", result)
        self.assertIn("CloudFormation", result)


class TestDataFlowDiagram(unittest.TestCase):
    """Tests for the data flow diagram."""

    def test_data_flow_generated_for_iac(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_data_flow_diagram()
        self.assertIn("flowchart LR", result)

    def test_data_flow_not_generated_without_resources(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_data_flow_diagram()
        self.assertEqual(result, "")

    def test_data_flow_has_subgraphs(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_data_flow_diagram()
        self.assertIn("Data Sources", result)
        self.assertIn("Network Layer", result)
        self.assertIn("Compute Layer", result)
        self.assertIn("Security & Config", result)

    def test_data_flow_has_emr_nodes(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_data_flow_diagram()
        self.assertIn("EMRMaster", result)
        self.assertIn("EMRCore", result)
        self.assertIn("EMRTask", result)

    def test_data_flow_has_classdefs(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_data_flow_diagram()
        self.assertIn("classDef storageNode", result)
        self.assertIn("classDef processNode", result)

    def test_data_flow_has_monitoring(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_data_flow_diagram()
        self.assertIn("CloudWatch", result)

    def test_data_flow_has_security_layer(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_data_flow_diagram()
        self.assertIn("IAMRoles", result)
        self.assertIn("SecurityGroups", result)

    def test_data_flow_has_network_topology(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_data_flow_diagram()
        self.assertIn("VPC", result)
        self.assertIn("PrivateSubnets", result)
        self.assertIn("NAT", result)
        self.assertIn("IGW", result)

    def test_data_flow_in_generate_all(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen.generate_all()
        self.assertIn("## Data Flow", result)

    def test_data_flow_has_processing_edges(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_VPC_ENDPOINTS})
        result = gen._generate_data_flow_diagram()
        self.assertIn("input datasets", result)
        self.assertIn("job distribution", result)


class TestCFIntegrationSequence(unittest.TestCase):
    """Tests for CloudFormation integration sequence diagram."""

    def test_cf_flow_generated(self):
        gen = MermaidDiagramGenerator({"cf": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._build_cf_integration_flow()
        self.assertIsNotNone(result)
        self.assertEqual(result[0], "Terraform-CloudFormation Integration")

    def test_cf_flow_not_generated_without_cf(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._build_cf_integration_flow()
        self.assertIsNone(result)

    def test_cf_flow_has_participants(self):
        gen = MermaidDiagramGenerator({"cf": SAMPLE_ARCH_CF_INTEGRATION})
        _, _, lines = gen._build_cf_integration_flow()
        content = "\n".join(lines)
        self.assertIn("participant Op as Operator", content)
        self.assertIn("participant TF as Terraform", content)
        self.assertIn("participant CF as AWS CloudFormation", content)
        self.assertIn("participant S3 as S3 Buckets", content)

    def test_cf_flow_has_stack_creation(self):
        gen = MermaidDiagramGenerator({"cf": SAMPLE_ARCH_CF_INTEGRATION})
        _, _, lines = gen._build_cf_integration_flow()
        content = "\n".join(lines)
        self.assertIn("Create/Update Stack", content)

    def test_cf_flow_has_polling_loop(self):
        gen = MermaidDiagramGenerator({"cf": SAMPLE_ARCH_CF_INTEGRATION})
        _, _, lines = gen._build_cf_integration_flow()
        content = "\n".join(lines)
        self.assertIn("loop Stack in progress", content)

    def test_cf_flow_has_outputs(self):
        gen = MermaidDiagramGenerator({"cf": SAMPLE_ARCH_CF_INTEGRATION})
        _, _, lines = gen._build_cf_integration_flow()
        content = "\n".join(lines)
        self.assertIn("CREATE_COMPLETE + Outputs", content)


class TestRuntimeSequence(unittest.TestCase):
    """Tests for EMR runtime/operational sequence diagram."""

    def test_runtime_flow_generated_for_emr(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._build_runtime_sequence_flow()
        self.assertIsNotNone(result)
        self.assertEqual(result[0], "EMR Job Submission")

    def test_runtime_flow_not_generated_without_emr(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._build_runtime_sequence_flow()
        self.assertIsNone(result)

    def test_runtime_flow_has_yarn(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        _, _, lines = gen._build_runtime_sequence_flow()
        content = "\n".join(lines)
        self.assertIn("YARN", content)

    def test_runtime_flow_has_alt_block(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        _, _, lines = gen._build_runtime_sequence_flow()
        content = "\n".join(lines)
        self.assertIn("alt Job Failed", content)

    def test_runtime_flow_has_s3_io(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        _, _, lines = gen._build_runtime_sequence_flow()
        content = "\n".join(lines)
        self.assertIn("Read input data", content)
        self.assertIn("Write output data", content)

    def test_runtime_flow_has_activate_deactivate(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        _, _, lines = gen._build_runtime_sequence_flow()
        content = "\n".join(lines)
        self.assertIn("activate EMR", content)
        self.assertIn("deactivate EMR", content)
        self.assertIn("activate YARN", content)
        self.assertIn("deactivate Workers", content)


class TestNarrativeGeneration(unittest.TestCase):
    """Tests for narrative text generation."""

    def test_key_connections_present_for_iac(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_key_connections_narrative()
        self.assertIn("## Key Connections", result)

    def test_key_connections_emr_mention(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_key_connections_narrative()
        self.assertIn("EMR", result)
        self.assertIn("Central Target", result)

    def test_key_connections_iam_mention(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_key_connections_narrative()
        self.assertIn("IAM", result)

    def test_key_connections_cf_bridge(self):
        gen = MermaidDiagramGenerator({
            "infra": SAMPLE_ARCH_IAC_WITH_RESOURCES,
            "cf": SAMPLE_ARCH_CF_INTEGRATION,
        })
        result = gen._generate_key_connections_narrative()
        self.assertIn("CloudFormation", result)

    def test_key_connections_empty_for_bare_repo(self):
        gen = MermaidDiagramGenerator({"repo1": SAMPLE_ARCH_CONTENT_1})
        result = gen._generate_key_connections_narrative()
        self.assertEqual(result, "")

    def test_data_flow_summary_table(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_data_flow_summary()
        self.assertIn("Data Type", result)
        self.assertIn("Flow Path", result)
        self.assertIn("Terraform State", result)

    def test_governance_concerns_present(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_governance_concerns()
        self.assertIn("Terraform State Exposure", result)
        self.assertIn("Recommendation", result)

    def test_governance_emr_hdfs(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_governance_concerns()
        self.assertIn("HDFS Encryption", result)

    def test_narrative_in_generate_all(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen.generate_all()
        self.assertIn("## Key Connections", result)
        self.assertIn("Data Flow Summary", result)
        self.assertIn("Governance Concerns", result)


class TestTechStackEnrichment(unittest.TestCase):
    """Tests for enriched tech stack diagram."""

    def test_tech_stack_cross_tech_edges(self):
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        result = gen._generate_tech_stack_diagram()
        # repo1 is in Docker + Terraform, should have cross-tech edge
        self.assertIn("-.->", result)

    def test_tech_stack_node_styling(self):
        gen = MermaidDiagramGenerator({
            "repo1": SAMPLE_ARCH_CONTENT_1,
            "repo2": SAMPLE_ARCH_CONTENT_2,
        })
        result = gen._generate_tech_stack_diagram()
        self.assertIn("class repo0", result)

    def test_tech_stack_single_tech_no_extra_edges(self):
        """Repo in only one tech group should not generate cross-tech edges."""
        content = """\
# hl_overview

**Repository Name:** single-tech

**Primary Language:** Python
**Total Files:** 5
**Total Lines of Code:** 100

**Technology Stack:**
- Python

**Language Breakdown:**

| Language | Files | Lines of Code | Blank | Comment |
|----------|------:|-------------:|------:|--------:|
| Python | 5 | 100 | 10 | 5 |
"""
        gen = MermaidDiagramGenerator({"repo": content})
        result = gen._generate_tech_stack_diagram()
        # No cross-tech edge since only one tech
        self.assertNotIn("-.->", result)


class TestSequenceFlowPriority(unittest.TestCase):
    """Tests for correct sequence diagram generation with new flows."""

    def test_iac_repos_get_all_flows(self):
        """IaC repos with EMR get IaC + Runtime flows."""
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_sequence_diagrams()
        self.assertIn("Infrastructure Provisioning", result)
        self.assertIn("EMR Job Submission", result)

    def test_cf_repo_gets_cf_flow(self):
        """CF repo gets CloudFormation integration flow."""
        gen = MermaidDiagramGenerator({"cf": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_sequence_diagrams()
        self.assertIn("Terraform-CloudFormation Integration", result)

    def test_combined_repos_get_multiple_flows(self):
        """Combined IaC + CF repos get both types of flows."""
        gen = MermaidDiagramGenerator({
            "infra": SAMPLE_ARCH_IAC_WITH_RESOURCES,
            "cf": SAMPLE_ARCH_CF_INTEGRATION,
        })
        result = gen._generate_sequence_diagrams()
        self.assertIn("Infrastructure Provisioning", result)
        self.assertIn("Terraform-CloudFormation Integration", result)


class TestDiagramTitles(unittest.TestCase):
    """Tests for Mermaid title front matter on all diagram types."""

    def test_overview_diagram_has_title(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_CONTENT_1, "r2": SAMPLE_ARCH_CONTENT_2})
        result = gen._generate_overview_diagram()
        self.assertIn("title: Network/Architecture Overview", result)

    def test_tech_stack_diagram_has_title(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_CONTENT_1, "r2": SAMPLE_ARCH_CONTENT_2})
        result = gen._generate_tech_stack_diagram()
        self.assertIn("title: Technology Stack", result)

    def test_infrastructure_diagram_has_title(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_infrastructure_diagram()
        self.assertIn("title: Infrastructure Architecture", result)

    def test_data_flow_diagram_has_title(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_data_flow_diagram()
        self.assertIn("title: Data Flow", result)

    def test_module_diagram_has_title(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_DEPS})
        result = gen._generate_module_diagrams()
        self.assertIn("title: Module Structure", result)

    def test_sequence_diagram_has_title(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_sequence_diagrams()
        # Each sequence flow should have a title in front matter
        self.assertIn("title: Infrastructure Provisioning Sequence", result)

    def test_sequence_cf_flow_has_title(self):
        gen = MermaidDiagramGenerator({"cf": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_sequence_diagrams()
        self.assertIn("title: Terraform-CloudFormation Integration", result)

    def test_sequence_runtime_flow_has_title(self):
        gen = MermaidDiagramGenerator({"infra": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_sequence_diagrams()
        self.assertIn("title: EMR Job Submission", result)

    def test_lifecycle_diagram_has_title(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES, "r2": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_cross_repo_lifecycle_diagram()
        self.assertIn("title: Cross-Repository Lifecycle", result)

    def test_title_uses_front_matter_format(self):
        """Titles should use the Mermaid ---\\ntitle:...\\n--- front matter format."""
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_CONTENT_1, "r2": SAMPLE_ARCH_CONTENT_2})
        result = gen._generate_overview_diagram()
        lines = result.split("\n")
        # Find the title line
        title_idx = None
        for i, line in enumerate(lines):
            if "title:" in line:
                title_idx = i
                break
        self.assertIsNotNone(title_idx, "Should have a title line")
        # Title should be between --- markers
        self.assertEqual(lines[title_idx - 1], "---")
        self.assertEqual(lines[title_idx + 1], "---")


class TestCrossRepoLifecycleDiagram(unittest.TestCase):
    """Tests for the overarching cross-repository lifecycle diagram."""

    def test_lifecycle_generated_for_multiple_repos(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES, "r2": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_cross_repo_lifecycle_diagram()
        self.assertIn("```mermaid", result)
        self.assertIn("graph LR", result)

    def test_lifecycle_not_generated_for_single_repo(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen._generate_cross_repo_lifecycle_diagram()
        self.assertEqual(result, "")

    def test_lifecycle_has_repo_nodes(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES, "r2": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_cross_repo_lifecycle_diagram()
        # Should contain nodes for each repo
        self.assertIn("LOC", result)
        self.assertIn("AWS Cloud", result)

    def test_lifecycle_has_aws_infrastructure_node(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES, "r2": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_cross_repo_lifecycle_diagram()
        self.assertIn("AWS_Infra", result)
        self.assertIn("provisions", result)

    def test_lifecycle_has_runtime_node_when_emr(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES, "r2": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_cross_repo_lifecycle_diagram()
        self.assertIn("Runtime", result)
        self.assertIn("enables", result)

    def test_lifecycle_shows_resource_summary(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES, "r2": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_cross_repo_lifecycle_diagram()
        # Should summarize what each repo provisions
        self.assertIn("VPC", result)
        self.assertIn("EMR", result)

    def test_lifecycle_has_styling(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES, "r2": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_cross_repo_lifecycle_diagram()
        self.assertIn("classDef", result)

    def test_lifecycle_alternative_iac_edges(self):
        """CF repos should show alternative IaC approach edges to non-CF EMR repos."""
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES, "r2": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen._generate_cross_repo_lifecycle_diagram()
        self.assertIn("alternative IaC approach", result)

    def test_lifecycle_in_generate_all(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES, "r2": SAMPLE_ARCH_CF_INTEGRATION})
        result = gen.generate_all()
        self.assertIn("## Cross-Repository Lifecycle", result)
        self.assertIn("Cross-Repository Lifecycle", result)

    def test_lifecycle_not_in_generate_all_single_repo(self):
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_IAC_WITH_RESOURCES})
        result = gen.generate_all()
        self.assertNotIn("## Cross-Repository Lifecycle", result)

    def test_lifecycle_basic_repos(self):
        """Even basic repos should show lifecycle if there are 2+."""
        gen = MermaidDiagramGenerator({"r1": SAMPLE_ARCH_CONTENT_1, "r2": SAMPLE_ARCH_CONTENT_2})
        result = gen._generate_cross_repo_lifecycle_diagram()
        self.assertIn("```mermaid", result)
        # Config since basic repos have no IaC resources
        self.assertIn("Config", result)


if __name__ == "__main__":
    unittest.main()
